// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module stereolbm_accel_addsub_0_0_ap_fixed_40_1_5_3_0_ap_fixed_40_1_0_3_0_ap_uint_1_s (
        ap_ready,
        a,
        b,
        add,
        ap_return
);


output   ap_ready;
input  [39:0] a;
input  [38:0] b;
input  [0:0] add;
output  [39:0] ap_return;

wire   [39:0] zext_ln1200_fu_36_p1;
wire   [39:0] ret_V_7_fu_46_p2;
wire   [39:0] ret_V_fu_40_p2;

assign ap_ready = 1'b1;

assign ap_return = ((add[0:0] == 1'b1) ? ret_V_7_fu_46_p2 : ret_V_fu_40_p2);

assign ret_V_7_fu_46_p2 = (zext_ln1200_fu_36_p1 + a);

assign ret_V_fu_40_p2 = (a - zext_ln1200_fu_36_p1);

assign zext_ln1200_fu_36_p1 = b;

endmodule //stereolbm_accel_addsub_0_0_ap_fixed_40_1_5_3_0_ap_fixed_40_1_0_3_0_ap_uint_1_s
