// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module stereolbm_accel_xfMat2AXILaser_1_720_1280_1_Pipeline_loop_ls_2axi (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        AXI_Laser_din,
        AXI_Laser_full_n,
        AXI_Laser_write,
        call_i_i4_reload,
        call_i_i8_reload,
        call_i_i12_reload,
        call_i_i16_reload,
        call_i_i21_reload,
        call_i_i25_reload,
        call_i_i29_reload,
        call_i_i33_reload,
        call_i_i37_reload,
        call_i_i41_reload,
        call_i_i45_reload,
        call_i_i49_reload,
        call_i_i53_reload,
        call_i_i57_reload,
        call_i_i61_reload,
        call_i_i65_reload,
        call_i_i69_reload,
        call_i_i73_reload,
        call_i_i77_reload,
        call_i_i81_reload,
        call_i_i85_reload,
        call_i_i89_reload,
        call_i_i93_reload,
        call_i_i97_reload,
        call_i_i101_reload,
        call_i_i105_reload,
        call_i_i109_reload,
        call_i_i113_reload,
        call_i_i117_reload,
        call_i_i121_reload,
        call_i_i125_reload,
        call_i_i129_reload,
        call_i_i133_reload,
        call_i_i137_reload,
        call_i_i141_reload,
        call_i_i145_reload,
        call_i_i149_reload,
        call_i_i153_reload,
        call_i_i157_reload,
        call_i_i161_reload,
        call_i_i165_reload,
        call_i_i169_reload,
        call_i_i173_reload,
        call_i_i177_reload,
        call_i_i181_reload,
        call_i_i185_reload,
        call_i_i189_reload,
        call_i_i193_reload,
        call_i_i197_reload,
        call_i_i201_reload,
        call_i_i205_reload,
        call_i_i209_reload,
        call_i_i213_reload,
        call_i_i217_reload,
        call_i_i221_reload,
        call_i_i225_reload,
        call_i_i229_reload,
        call_i_i233_reload,
        call_i_i237_reload,
        call_i_i241_reload,
        call_i_i245_reload,
        call_i_i249_reload,
        call_i_i253_reload,
        call_i_i257_reload,
        call_i_i261_reload,
        call_i_i265_reload,
        call_i_i269_reload,
        call_i_i273_reload,
        call_i_i277_reload,
        call_i_i281_reload,
        call_i_i285_reload,
        call_i_i289_reload,
        call_i_i293_reload,
        call_i_i297_reload,
        call_i_i301_reload,
        call_i_i305_reload,
        call_i_i309_reload,
        call_i_i313_reload,
        call_i_i317_reload,
        call_i_i321_reload,
        call_i_i325_reload,
        call_i_i329_reload,
        call_i_i333_reload,
        call_i_i337_reload,
        call_i_i341_reload,
        call_i_i345_reload,
        call_i_i349_reload,
        call_i_i353_reload,
        call_i_i357_reload,
        call_i_i361_reload,
        call_i_i365_reload,
        call_i_i369_reload,
        call_i_i373_reload,
        call_i_i377_reload,
        call_i_i381_reload,
        call_i_i385_reload,
        call_i_i389_reload,
        call_i_i393_reload,
        call_i_i397_reload,
        call_i_i401_reload,
        call_i_i405_reload,
        call_i_i409_reload,
        call_i_i413_reload,
        call_i_i417_reload,
        call_i_i421_reload,
        call_i_i425_reload,
        call_i_i429_reload,
        call_i_i433_reload,
        call_i_i437_reload,
        call_i_i441_reload,
        call_i_i445_reload,
        call_i_i449_reload,
        call_i_i453_reload,
        call_i_i457_reload,
        call_i_i461_reload,
        call_i_i465_reload,
        call_i_i469_reload,
        call_i_i473_reload,
        call_i_i477_reload,
        call_i_i481_reload,
        call_i_i485_reload,
        call_i_i489_reload,
        call_i_i493_reload,
        call_i_i497_reload,
        call_i_i501_reload,
        call_i_i505_reload,
        call_i_i509_reload,
        call_i_i513_reload,
        call_i_i517_reload,
        call_i_i521_reload,
        call_i_i525_reload,
        call_i_i529_reload,
        call_i_i533_reload,
        call_i_i537_reload,
        call_i_i541_reload,
        call_i_i545_reload,
        call_i_i549_reload,
        call_i_i553_reload,
        call_i_i557_reload,
        call_i_i561_reload,
        call_i_i565_reload,
        call_i_i569_reload,
        call_i_i573_reload,
        call_i_i577_reload,
        call_i_i581_reload,
        call_i_i585_reload,
        call_i_i589_reload,
        call_i_i593_reload,
        call_i_i597_reload,
        call_i_i601_reload,
        call_i_i605_reload,
        call_i_i609_reload,
        call_i_i613_reload,
        call_i_i617_reload,
        call_i_i621_reload,
        call_i_i625_reload,
        call_i_i629_reload,
        call_i_i633_reload,
        call_i_i637_reload,
        call_i_i641_reload,
        call_i_i645_reload,
        call_i_i649_reload,
        call_i_i653_reload,
        call_i_i657_reload,
        call_i_i661_reload,
        call_i_i665_reload,
        call_i_i669_reload,
        call_i_i673_reload,
        call_i_i677_reload,
        call_i_i681_reload,
        call_i_i685_reload,
        call_i_i689_reload,
        call_i_i693_reload,
        call_i_i697_reload,
        call_i_i701_reload,
        call_i_i705_reload,
        call_i_i709_reload,
        call_i_i713_reload,
        call_i_i717_reload,
        call_i_i721_reload,
        call_i_i725_reload,
        call_i_i729_reload,
        call_i_i733_reload,
        call_i_i737_reload,
        call_i_i741_reload,
        call_i_i745_reload,
        call_i_i749_reload,
        call_i_i753_reload,
        call_i_i757_reload,
        call_i_i761_reload,
        call_i_i765_reload,
        call_i_i769_reload,
        call_i_i773_reload,
        call_i_i777_reload,
        call_i_i781_reload,
        call_i_i785_reload,
        call_i_i789_reload,
        call_i_i793_reload,
        call_i_i797_reload,
        call_i_i801_reload,
        call_i_i805_reload,
        call_i_i809_reload,
        call_i_i813_reload,
        call_i_i817_reload,
        call_i_i821_reload,
        call_i_i825_reload,
        call_i_i829_reload,
        call_i_i833_reload,
        call_i_i837_reload,
        call_i_i841_reload,
        call_i_i845_reload,
        call_i_i849_reload,
        call_i_i853_reload,
        call_i_i857_reload,
        call_i_i861_reload,
        call_i_i865_reload,
        call_i_i869_reload,
        call_i_i873_reload,
        call_i_i877_reload,
        call_i_i881_reload,
        call_i_i885_reload,
        call_i_i889_reload,
        call_i_i893_reload,
        call_i_i897_reload,
        call_i_i901_reload,
        call_i_i905_reload,
        call_i_i909_reload,
        call_i_i913_reload,
        call_i_i917_reload,
        call_i_i921_reload,
        call_i_i925_reload,
        call_i_i929_reload,
        call_i_i933_reload,
        call_i_i937_reload,
        call_i_i941_reload,
        call_i_i945_reload,
        call_i_i949_reload,
        call_i_i953_reload,
        call_i_i957_reload,
        call_i_i961_reload,
        call_i_i965_reload
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [8:0] AXI_Laser_din;
input   AXI_Laser_full_n;
output   AXI_Laser_write;
input  [31:0] call_i_i4_reload;
input  [31:0] call_i_i8_reload;
input  [31:0] call_i_i12_reload;
input  [31:0] call_i_i16_reload;
input  [31:0] call_i_i21_reload;
input  [31:0] call_i_i25_reload;
input  [31:0] call_i_i29_reload;
input  [31:0] call_i_i33_reload;
input  [31:0] call_i_i37_reload;
input  [31:0] call_i_i41_reload;
input  [31:0] call_i_i45_reload;
input  [31:0] call_i_i49_reload;
input  [31:0] call_i_i53_reload;
input  [31:0] call_i_i57_reload;
input  [31:0] call_i_i61_reload;
input  [31:0] call_i_i65_reload;
input  [31:0] call_i_i69_reload;
input  [31:0] call_i_i73_reload;
input  [31:0] call_i_i77_reload;
input  [31:0] call_i_i81_reload;
input  [31:0] call_i_i85_reload;
input  [31:0] call_i_i89_reload;
input  [31:0] call_i_i93_reload;
input  [31:0] call_i_i97_reload;
input  [31:0] call_i_i101_reload;
input  [31:0] call_i_i105_reload;
input  [31:0] call_i_i109_reload;
input  [31:0] call_i_i113_reload;
input  [31:0] call_i_i117_reload;
input  [31:0] call_i_i121_reload;
input  [31:0] call_i_i125_reload;
input  [31:0] call_i_i129_reload;
input  [31:0] call_i_i133_reload;
input  [31:0] call_i_i137_reload;
input  [31:0] call_i_i141_reload;
input  [31:0] call_i_i145_reload;
input  [31:0] call_i_i149_reload;
input  [31:0] call_i_i153_reload;
input  [31:0] call_i_i157_reload;
input  [31:0] call_i_i161_reload;
input  [31:0] call_i_i165_reload;
input  [31:0] call_i_i169_reload;
input  [31:0] call_i_i173_reload;
input  [31:0] call_i_i177_reload;
input  [31:0] call_i_i181_reload;
input  [31:0] call_i_i185_reload;
input  [31:0] call_i_i189_reload;
input  [31:0] call_i_i193_reload;
input  [31:0] call_i_i197_reload;
input  [31:0] call_i_i201_reload;
input  [31:0] call_i_i205_reload;
input  [31:0] call_i_i209_reload;
input  [31:0] call_i_i213_reload;
input  [31:0] call_i_i217_reload;
input  [31:0] call_i_i221_reload;
input  [31:0] call_i_i225_reload;
input  [31:0] call_i_i229_reload;
input  [31:0] call_i_i233_reload;
input  [31:0] call_i_i237_reload;
input  [31:0] call_i_i241_reload;
input  [31:0] call_i_i245_reload;
input  [31:0] call_i_i249_reload;
input  [31:0] call_i_i253_reload;
input  [31:0] call_i_i257_reload;
input  [31:0] call_i_i261_reload;
input  [31:0] call_i_i265_reload;
input  [31:0] call_i_i269_reload;
input  [31:0] call_i_i273_reload;
input  [31:0] call_i_i277_reload;
input  [31:0] call_i_i281_reload;
input  [31:0] call_i_i285_reload;
input  [31:0] call_i_i289_reload;
input  [31:0] call_i_i293_reload;
input  [31:0] call_i_i297_reload;
input  [31:0] call_i_i301_reload;
input  [31:0] call_i_i305_reload;
input  [31:0] call_i_i309_reload;
input  [31:0] call_i_i313_reload;
input  [31:0] call_i_i317_reload;
input  [31:0] call_i_i321_reload;
input  [31:0] call_i_i325_reload;
input  [31:0] call_i_i329_reload;
input  [31:0] call_i_i333_reload;
input  [31:0] call_i_i337_reload;
input  [31:0] call_i_i341_reload;
input  [31:0] call_i_i345_reload;
input  [31:0] call_i_i349_reload;
input  [31:0] call_i_i353_reload;
input  [31:0] call_i_i357_reload;
input  [31:0] call_i_i361_reload;
input  [31:0] call_i_i365_reload;
input  [31:0] call_i_i369_reload;
input  [31:0] call_i_i373_reload;
input  [31:0] call_i_i377_reload;
input  [31:0] call_i_i381_reload;
input  [31:0] call_i_i385_reload;
input  [31:0] call_i_i389_reload;
input  [31:0] call_i_i393_reload;
input  [31:0] call_i_i397_reload;
input  [31:0] call_i_i401_reload;
input  [31:0] call_i_i405_reload;
input  [31:0] call_i_i409_reload;
input  [31:0] call_i_i413_reload;
input  [31:0] call_i_i417_reload;
input  [31:0] call_i_i421_reload;
input  [31:0] call_i_i425_reload;
input  [31:0] call_i_i429_reload;
input  [31:0] call_i_i433_reload;
input  [31:0] call_i_i437_reload;
input  [31:0] call_i_i441_reload;
input  [31:0] call_i_i445_reload;
input  [31:0] call_i_i449_reload;
input  [31:0] call_i_i453_reload;
input  [31:0] call_i_i457_reload;
input  [31:0] call_i_i461_reload;
input  [31:0] call_i_i465_reload;
input  [31:0] call_i_i469_reload;
input  [31:0] call_i_i473_reload;
input  [31:0] call_i_i477_reload;
input  [31:0] call_i_i481_reload;
input  [31:0] call_i_i485_reload;
input  [31:0] call_i_i489_reload;
input  [31:0] call_i_i493_reload;
input  [31:0] call_i_i497_reload;
input  [31:0] call_i_i501_reload;
input  [31:0] call_i_i505_reload;
input  [31:0] call_i_i509_reload;
input  [31:0] call_i_i513_reload;
input  [31:0] call_i_i517_reload;
input  [31:0] call_i_i521_reload;
input  [31:0] call_i_i525_reload;
input  [31:0] call_i_i529_reload;
input  [31:0] call_i_i533_reload;
input  [31:0] call_i_i537_reload;
input  [31:0] call_i_i541_reload;
input  [31:0] call_i_i545_reload;
input  [31:0] call_i_i549_reload;
input  [31:0] call_i_i553_reload;
input  [31:0] call_i_i557_reload;
input  [31:0] call_i_i561_reload;
input  [31:0] call_i_i565_reload;
input  [31:0] call_i_i569_reload;
input  [31:0] call_i_i573_reload;
input  [31:0] call_i_i577_reload;
input  [31:0] call_i_i581_reload;
input  [31:0] call_i_i585_reload;
input  [31:0] call_i_i589_reload;
input  [31:0] call_i_i593_reload;
input  [31:0] call_i_i597_reload;
input  [31:0] call_i_i601_reload;
input  [31:0] call_i_i605_reload;
input  [31:0] call_i_i609_reload;
input  [31:0] call_i_i613_reload;
input  [31:0] call_i_i617_reload;
input  [31:0] call_i_i621_reload;
input  [31:0] call_i_i625_reload;
input  [31:0] call_i_i629_reload;
input  [31:0] call_i_i633_reload;
input  [31:0] call_i_i637_reload;
input  [31:0] call_i_i641_reload;
input  [31:0] call_i_i645_reload;
input  [31:0] call_i_i649_reload;
input  [31:0] call_i_i653_reload;
input  [31:0] call_i_i657_reload;
input  [31:0] call_i_i661_reload;
input  [31:0] call_i_i665_reload;
input  [31:0] call_i_i669_reload;
input  [31:0] call_i_i673_reload;
input  [31:0] call_i_i677_reload;
input  [31:0] call_i_i681_reload;
input  [31:0] call_i_i685_reload;
input  [31:0] call_i_i689_reload;
input  [31:0] call_i_i693_reload;
input  [31:0] call_i_i697_reload;
input  [31:0] call_i_i701_reload;
input  [31:0] call_i_i705_reload;
input  [31:0] call_i_i709_reload;
input  [31:0] call_i_i713_reload;
input  [31:0] call_i_i717_reload;
input  [31:0] call_i_i721_reload;
input  [31:0] call_i_i725_reload;
input  [31:0] call_i_i729_reload;
input  [31:0] call_i_i733_reload;
input  [31:0] call_i_i737_reload;
input  [31:0] call_i_i741_reload;
input  [31:0] call_i_i745_reload;
input  [31:0] call_i_i749_reload;
input  [31:0] call_i_i753_reload;
input  [31:0] call_i_i757_reload;
input  [31:0] call_i_i761_reload;
input  [31:0] call_i_i765_reload;
input  [31:0] call_i_i769_reload;
input  [31:0] call_i_i773_reload;
input  [31:0] call_i_i777_reload;
input  [31:0] call_i_i781_reload;
input  [31:0] call_i_i785_reload;
input  [31:0] call_i_i789_reload;
input  [31:0] call_i_i793_reload;
input  [31:0] call_i_i797_reload;
input  [31:0] call_i_i801_reload;
input  [31:0] call_i_i805_reload;
input  [31:0] call_i_i809_reload;
input  [31:0] call_i_i813_reload;
input  [31:0] call_i_i817_reload;
input  [31:0] call_i_i821_reload;
input  [31:0] call_i_i825_reload;
input  [31:0] call_i_i829_reload;
input  [31:0] call_i_i833_reload;
input  [31:0] call_i_i837_reload;
input  [31:0] call_i_i841_reload;
input  [31:0] call_i_i845_reload;
input  [31:0] call_i_i849_reload;
input  [31:0] call_i_i853_reload;
input  [31:0] call_i_i857_reload;
input  [31:0] call_i_i861_reload;
input  [31:0] call_i_i865_reload;
input  [31:0] call_i_i869_reload;
input  [31:0] call_i_i873_reload;
input  [31:0] call_i_i877_reload;
input  [31:0] call_i_i881_reload;
input  [31:0] call_i_i885_reload;
input  [31:0] call_i_i889_reload;
input  [31:0] call_i_i893_reload;
input  [31:0] call_i_i897_reload;
input  [31:0] call_i_i901_reload;
input  [31:0] call_i_i905_reload;
input  [31:0] call_i_i909_reload;
input  [31:0] call_i_i913_reload;
input  [31:0] call_i_i917_reload;
input  [31:0] call_i_i921_reload;
input  [31:0] call_i_i925_reload;
input  [31:0] call_i_i929_reload;
input  [31:0] call_i_i933_reload;
input  [31:0] call_i_i937_reload;
input  [31:0] call_i_i941_reload;
input  [31:0] call_i_i945_reload;
input  [31:0] call_i_i949_reload;
input  [31:0] call_i_i953_reload;
input  [31:0] call_i_i957_reload;
input  [31:0] call_i_i961_reload;
input  [31:0] call_i_i965_reload;

reg ap_idle;
reg AXI_Laser_write;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln249_fu_2019_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    AXI_Laser_blk_n;
wire    ap_block_pp0_stage0;
wire   [0:0] tmp_V_fu_2031_p2;
reg   [0:0] tmp_V_reg_2795;
reg    ap_block_pp0_stage0_11001;
wire   [7:0] pixelpacket_data_V_fu_2765_p3;
reg   [7:0] pixelpacket_data_V_reg_2800;
reg   [7:0] i_fu_554;
wire   [7:0] add_ln249_fu_2025_p2;
wire    ap_loop_init;
reg   [7:0] ap_sig_allocacmp_i_1;
reg    ap_block_pp0_stage0_01001;
wire   [31:0] val_fu_2037_p243;
wire   [31:0] reg_fu_2525_p1;
wire   [7:0] exp_fu_2541_p4;
wire   [22:0] trunc_ln287_fu_2555_p1;
wire   [30:0] trunc_ln278_fu_2529_p1;
wire   [8:0] zext_ln283_fu_2551_p1;
wire  signed [8:0] sh_amt_fu_2577_p2;
wire   [6:0] trunc_ln298_fu_2583_p1;
wire   [6:0] sh_amt_1_fu_2609_p2;
wire   [3:0] tmp_fu_2615_p4;
wire   [23:0] tmp_4_fu_2563_p3;
wire   [31:0] zext_ln304_fu_2631_p1;
wire  signed [31:0] sext_ln298_fu_2587_p1;
wire   [31:0] lshr_ln304_fu_2635_p2;
wire   [7:0] trunc_ln300_fu_2559_p1;
wire   [7:0] sh_amt_1cast_fu_2645_p1;
wire   [0:0] icmp_ln295_fu_2571_p2;
wire   [0:0] icmp_ln299_fu_2591_p2;
wire   [0:0] or_ln299_fu_2655_p2;
wire   [0:0] icmp_ln301_fu_2597_p2;
wire   [0:0] xor_ln299_fu_2661_p2;
wire   [0:0] and_ln301_fu_2667_p2;
wire   [0:0] icmp_ln302_fu_2603_p2;
wire   [0:0] and_ln302_fu_2673_p2;
wire   [7:0] trunc_ln311_fu_2641_p1;
wire   [0:0] or_ln301_fu_2687_p2;
wire   [0:0] icmp_ln320_fu_2625_p2;
wire   [0:0] xor_ln301_fu_2693_p2;
wire   [0:0] and_ln320_fu_2699_p2;
wire   [7:0] shl_ln322_fu_2649_p2;
wire   [7:0] select_ln302_fu_2679_p3;
wire   [0:0] xor_ln302_fu_2713_p2;
wire   [0:0] and_ln302_1_fu_2719_p2;
wire   [0:0] or_ln302_fu_2725_p2;
wire   [7:0] select_ln320_fu_2705_p3;
wire   [0:0] xor_ln295_fu_2739_p2;
wire   [0:0] and_ln299_fu_2745_p2;
wire   [7:0] select_ln302_1_fu_2731_p3;
wire   [7:0] select_ln299_fu_2751_p3;
wire   [0:0] p_Result_s_fu_2533_p3;
wire   [7:0] sub_ln501_fu_2759_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

stereolbm_accel_mux_2418_32_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .din2_WIDTH( 32 ),
    .din3_WIDTH( 32 ),
    .din4_WIDTH( 32 ),
    .din5_WIDTH( 32 ),
    .din6_WIDTH( 32 ),
    .din7_WIDTH( 32 ),
    .din8_WIDTH( 32 ),
    .din9_WIDTH( 32 ),
    .din10_WIDTH( 32 ),
    .din11_WIDTH( 32 ),
    .din12_WIDTH( 32 ),
    .din13_WIDTH( 32 ),
    .din14_WIDTH( 32 ),
    .din15_WIDTH( 32 ),
    .din16_WIDTH( 32 ),
    .din17_WIDTH( 32 ),
    .din18_WIDTH( 32 ),
    .din19_WIDTH( 32 ),
    .din20_WIDTH( 32 ),
    .din21_WIDTH( 32 ),
    .din22_WIDTH( 32 ),
    .din23_WIDTH( 32 ),
    .din24_WIDTH( 32 ),
    .din25_WIDTH( 32 ),
    .din26_WIDTH( 32 ),
    .din27_WIDTH( 32 ),
    .din28_WIDTH( 32 ),
    .din29_WIDTH( 32 ),
    .din30_WIDTH( 32 ),
    .din31_WIDTH( 32 ),
    .din32_WIDTH( 32 ),
    .din33_WIDTH( 32 ),
    .din34_WIDTH( 32 ),
    .din35_WIDTH( 32 ),
    .din36_WIDTH( 32 ),
    .din37_WIDTH( 32 ),
    .din38_WIDTH( 32 ),
    .din39_WIDTH( 32 ),
    .din40_WIDTH( 32 ),
    .din41_WIDTH( 32 ),
    .din42_WIDTH( 32 ),
    .din43_WIDTH( 32 ),
    .din44_WIDTH( 32 ),
    .din45_WIDTH( 32 ),
    .din46_WIDTH( 32 ),
    .din47_WIDTH( 32 ),
    .din48_WIDTH( 32 ),
    .din49_WIDTH( 32 ),
    .din50_WIDTH( 32 ),
    .din51_WIDTH( 32 ),
    .din52_WIDTH( 32 ),
    .din53_WIDTH( 32 ),
    .din54_WIDTH( 32 ),
    .din55_WIDTH( 32 ),
    .din56_WIDTH( 32 ),
    .din57_WIDTH( 32 ),
    .din58_WIDTH( 32 ),
    .din59_WIDTH( 32 ),
    .din60_WIDTH( 32 ),
    .din61_WIDTH( 32 ),
    .din62_WIDTH( 32 ),
    .din63_WIDTH( 32 ),
    .din64_WIDTH( 32 ),
    .din65_WIDTH( 32 ),
    .din66_WIDTH( 32 ),
    .din67_WIDTH( 32 ),
    .din68_WIDTH( 32 ),
    .din69_WIDTH( 32 ),
    .din70_WIDTH( 32 ),
    .din71_WIDTH( 32 ),
    .din72_WIDTH( 32 ),
    .din73_WIDTH( 32 ),
    .din74_WIDTH( 32 ),
    .din75_WIDTH( 32 ),
    .din76_WIDTH( 32 ),
    .din77_WIDTH( 32 ),
    .din78_WIDTH( 32 ),
    .din79_WIDTH( 32 ),
    .din80_WIDTH( 32 ),
    .din81_WIDTH( 32 ),
    .din82_WIDTH( 32 ),
    .din83_WIDTH( 32 ),
    .din84_WIDTH( 32 ),
    .din85_WIDTH( 32 ),
    .din86_WIDTH( 32 ),
    .din87_WIDTH( 32 ),
    .din88_WIDTH( 32 ),
    .din89_WIDTH( 32 ),
    .din90_WIDTH( 32 ),
    .din91_WIDTH( 32 ),
    .din92_WIDTH( 32 ),
    .din93_WIDTH( 32 ),
    .din94_WIDTH( 32 ),
    .din95_WIDTH( 32 ),
    .din96_WIDTH( 32 ),
    .din97_WIDTH( 32 ),
    .din98_WIDTH( 32 ),
    .din99_WIDTH( 32 ),
    .din100_WIDTH( 32 ),
    .din101_WIDTH( 32 ),
    .din102_WIDTH( 32 ),
    .din103_WIDTH( 32 ),
    .din104_WIDTH( 32 ),
    .din105_WIDTH( 32 ),
    .din106_WIDTH( 32 ),
    .din107_WIDTH( 32 ),
    .din108_WIDTH( 32 ),
    .din109_WIDTH( 32 ),
    .din110_WIDTH( 32 ),
    .din111_WIDTH( 32 ),
    .din112_WIDTH( 32 ),
    .din113_WIDTH( 32 ),
    .din114_WIDTH( 32 ),
    .din115_WIDTH( 32 ),
    .din116_WIDTH( 32 ),
    .din117_WIDTH( 32 ),
    .din118_WIDTH( 32 ),
    .din119_WIDTH( 32 ),
    .din120_WIDTH( 32 ),
    .din121_WIDTH( 32 ),
    .din122_WIDTH( 32 ),
    .din123_WIDTH( 32 ),
    .din124_WIDTH( 32 ),
    .din125_WIDTH( 32 ),
    .din126_WIDTH( 32 ),
    .din127_WIDTH( 32 ),
    .din128_WIDTH( 32 ),
    .din129_WIDTH( 32 ),
    .din130_WIDTH( 32 ),
    .din131_WIDTH( 32 ),
    .din132_WIDTH( 32 ),
    .din133_WIDTH( 32 ),
    .din134_WIDTH( 32 ),
    .din135_WIDTH( 32 ),
    .din136_WIDTH( 32 ),
    .din137_WIDTH( 32 ),
    .din138_WIDTH( 32 ),
    .din139_WIDTH( 32 ),
    .din140_WIDTH( 32 ),
    .din141_WIDTH( 32 ),
    .din142_WIDTH( 32 ),
    .din143_WIDTH( 32 ),
    .din144_WIDTH( 32 ),
    .din145_WIDTH( 32 ),
    .din146_WIDTH( 32 ),
    .din147_WIDTH( 32 ),
    .din148_WIDTH( 32 ),
    .din149_WIDTH( 32 ),
    .din150_WIDTH( 32 ),
    .din151_WIDTH( 32 ),
    .din152_WIDTH( 32 ),
    .din153_WIDTH( 32 ),
    .din154_WIDTH( 32 ),
    .din155_WIDTH( 32 ),
    .din156_WIDTH( 32 ),
    .din157_WIDTH( 32 ),
    .din158_WIDTH( 32 ),
    .din159_WIDTH( 32 ),
    .din160_WIDTH( 32 ),
    .din161_WIDTH( 32 ),
    .din162_WIDTH( 32 ),
    .din163_WIDTH( 32 ),
    .din164_WIDTH( 32 ),
    .din165_WIDTH( 32 ),
    .din166_WIDTH( 32 ),
    .din167_WIDTH( 32 ),
    .din168_WIDTH( 32 ),
    .din169_WIDTH( 32 ),
    .din170_WIDTH( 32 ),
    .din171_WIDTH( 32 ),
    .din172_WIDTH( 32 ),
    .din173_WIDTH( 32 ),
    .din174_WIDTH( 32 ),
    .din175_WIDTH( 32 ),
    .din176_WIDTH( 32 ),
    .din177_WIDTH( 32 ),
    .din178_WIDTH( 32 ),
    .din179_WIDTH( 32 ),
    .din180_WIDTH( 32 ),
    .din181_WIDTH( 32 ),
    .din182_WIDTH( 32 ),
    .din183_WIDTH( 32 ),
    .din184_WIDTH( 32 ),
    .din185_WIDTH( 32 ),
    .din186_WIDTH( 32 ),
    .din187_WIDTH( 32 ),
    .din188_WIDTH( 32 ),
    .din189_WIDTH( 32 ),
    .din190_WIDTH( 32 ),
    .din191_WIDTH( 32 ),
    .din192_WIDTH( 32 ),
    .din193_WIDTH( 32 ),
    .din194_WIDTH( 32 ),
    .din195_WIDTH( 32 ),
    .din196_WIDTH( 32 ),
    .din197_WIDTH( 32 ),
    .din198_WIDTH( 32 ),
    .din199_WIDTH( 32 ),
    .din200_WIDTH( 32 ),
    .din201_WIDTH( 32 ),
    .din202_WIDTH( 32 ),
    .din203_WIDTH( 32 ),
    .din204_WIDTH( 32 ),
    .din205_WIDTH( 32 ),
    .din206_WIDTH( 32 ),
    .din207_WIDTH( 32 ),
    .din208_WIDTH( 32 ),
    .din209_WIDTH( 32 ),
    .din210_WIDTH( 32 ),
    .din211_WIDTH( 32 ),
    .din212_WIDTH( 32 ),
    .din213_WIDTH( 32 ),
    .din214_WIDTH( 32 ),
    .din215_WIDTH( 32 ),
    .din216_WIDTH( 32 ),
    .din217_WIDTH( 32 ),
    .din218_WIDTH( 32 ),
    .din219_WIDTH( 32 ),
    .din220_WIDTH( 32 ),
    .din221_WIDTH( 32 ),
    .din222_WIDTH( 32 ),
    .din223_WIDTH( 32 ),
    .din224_WIDTH( 32 ),
    .din225_WIDTH( 32 ),
    .din226_WIDTH( 32 ),
    .din227_WIDTH( 32 ),
    .din228_WIDTH( 32 ),
    .din229_WIDTH( 32 ),
    .din230_WIDTH( 32 ),
    .din231_WIDTH( 32 ),
    .din232_WIDTH( 32 ),
    .din233_WIDTH( 32 ),
    .din234_WIDTH( 32 ),
    .din235_WIDTH( 32 ),
    .din236_WIDTH( 32 ),
    .din237_WIDTH( 32 ),
    .din238_WIDTH( 32 ),
    .din239_WIDTH( 32 ),
    .din240_WIDTH( 32 ),
    .din241_WIDTH( 8 ),
    .dout_WIDTH( 32 ))
mux_2418_32_1_1_U1029(
    .din0(call_i_i4_reload),
    .din1(call_i_i8_reload),
    .din2(call_i_i12_reload),
    .din3(call_i_i16_reload),
    .din4(call_i_i21_reload),
    .din5(call_i_i25_reload),
    .din6(call_i_i29_reload),
    .din7(call_i_i33_reload),
    .din8(call_i_i37_reload),
    .din9(call_i_i41_reload),
    .din10(call_i_i45_reload),
    .din11(call_i_i49_reload),
    .din12(call_i_i53_reload),
    .din13(call_i_i57_reload),
    .din14(call_i_i61_reload),
    .din15(call_i_i65_reload),
    .din16(call_i_i69_reload),
    .din17(call_i_i73_reload),
    .din18(call_i_i77_reload),
    .din19(call_i_i81_reload),
    .din20(call_i_i85_reload),
    .din21(call_i_i89_reload),
    .din22(call_i_i93_reload),
    .din23(call_i_i97_reload),
    .din24(call_i_i101_reload),
    .din25(call_i_i105_reload),
    .din26(call_i_i109_reload),
    .din27(call_i_i113_reload),
    .din28(call_i_i117_reload),
    .din29(call_i_i121_reload),
    .din30(call_i_i125_reload),
    .din31(call_i_i129_reload),
    .din32(call_i_i133_reload),
    .din33(call_i_i137_reload),
    .din34(call_i_i141_reload),
    .din35(call_i_i145_reload),
    .din36(call_i_i149_reload),
    .din37(call_i_i153_reload),
    .din38(call_i_i157_reload),
    .din39(call_i_i161_reload),
    .din40(call_i_i165_reload),
    .din41(call_i_i169_reload),
    .din42(call_i_i173_reload),
    .din43(call_i_i177_reload),
    .din44(call_i_i181_reload),
    .din45(call_i_i185_reload),
    .din46(call_i_i189_reload),
    .din47(call_i_i193_reload),
    .din48(call_i_i197_reload),
    .din49(call_i_i201_reload),
    .din50(call_i_i205_reload),
    .din51(call_i_i209_reload),
    .din52(call_i_i213_reload),
    .din53(call_i_i217_reload),
    .din54(call_i_i221_reload),
    .din55(call_i_i225_reload),
    .din56(call_i_i229_reload),
    .din57(call_i_i233_reload),
    .din58(call_i_i237_reload),
    .din59(call_i_i241_reload),
    .din60(call_i_i245_reload),
    .din61(call_i_i249_reload),
    .din62(call_i_i253_reload),
    .din63(call_i_i257_reload),
    .din64(call_i_i261_reload),
    .din65(call_i_i265_reload),
    .din66(call_i_i269_reload),
    .din67(call_i_i273_reload),
    .din68(call_i_i277_reload),
    .din69(call_i_i281_reload),
    .din70(call_i_i285_reload),
    .din71(call_i_i289_reload),
    .din72(call_i_i293_reload),
    .din73(call_i_i297_reload),
    .din74(call_i_i301_reload),
    .din75(call_i_i305_reload),
    .din76(call_i_i309_reload),
    .din77(call_i_i313_reload),
    .din78(call_i_i317_reload),
    .din79(call_i_i321_reload),
    .din80(call_i_i325_reload),
    .din81(call_i_i329_reload),
    .din82(call_i_i333_reload),
    .din83(call_i_i337_reload),
    .din84(call_i_i341_reload),
    .din85(call_i_i345_reload),
    .din86(call_i_i349_reload),
    .din87(call_i_i353_reload),
    .din88(call_i_i357_reload),
    .din89(call_i_i361_reload),
    .din90(call_i_i365_reload),
    .din91(call_i_i369_reload),
    .din92(call_i_i373_reload),
    .din93(call_i_i377_reload),
    .din94(call_i_i381_reload),
    .din95(call_i_i385_reload),
    .din96(call_i_i389_reload),
    .din97(call_i_i393_reload),
    .din98(call_i_i397_reload),
    .din99(call_i_i401_reload),
    .din100(call_i_i405_reload),
    .din101(call_i_i409_reload),
    .din102(call_i_i413_reload),
    .din103(call_i_i417_reload),
    .din104(call_i_i421_reload),
    .din105(call_i_i425_reload),
    .din106(call_i_i429_reload),
    .din107(call_i_i433_reload),
    .din108(call_i_i437_reload),
    .din109(call_i_i441_reload),
    .din110(call_i_i445_reload),
    .din111(call_i_i449_reload),
    .din112(call_i_i453_reload),
    .din113(call_i_i457_reload),
    .din114(call_i_i461_reload),
    .din115(call_i_i465_reload),
    .din116(call_i_i469_reload),
    .din117(call_i_i473_reload),
    .din118(call_i_i477_reload),
    .din119(call_i_i481_reload),
    .din120(call_i_i485_reload),
    .din121(call_i_i489_reload),
    .din122(call_i_i493_reload),
    .din123(call_i_i497_reload),
    .din124(call_i_i501_reload),
    .din125(call_i_i505_reload),
    .din126(call_i_i509_reload),
    .din127(call_i_i513_reload),
    .din128(call_i_i517_reload),
    .din129(call_i_i521_reload),
    .din130(call_i_i525_reload),
    .din131(call_i_i529_reload),
    .din132(call_i_i533_reload),
    .din133(call_i_i537_reload),
    .din134(call_i_i541_reload),
    .din135(call_i_i545_reload),
    .din136(call_i_i549_reload),
    .din137(call_i_i553_reload),
    .din138(call_i_i557_reload),
    .din139(call_i_i561_reload),
    .din140(call_i_i565_reload),
    .din141(call_i_i569_reload),
    .din142(call_i_i573_reload),
    .din143(call_i_i577_reload),
    .din144(call_i_i581_reload),
    .din145(call_i_i585_reload),
    .din146(call_i_i589_reload),
    .din147(call_i_i593_reload),
    .din148(call_i_i597_reload),
    .din149(call_i_i601_reload),
    .din150(call_i_i605_reload),
    .din151(call_i_i609_reload),
    .din152(call_i_i613_reload),
    .din153(call_i_i617_reload),
    .din154(call_i_i621_reload),
    .din155(call_i_i625_reload),
    .din156(call_i_i629_reload),
    .din157(call_i_i633_reload),
    .din158(call_i_i637_reload),
    .din159(call_i_i641_reload),
    .din160(call_i_i645_reload),
    .din161(call_i_i649_reload),
    .din162(call_i_i653_reload),
    .din163(call_i_i657_reload),
    .din164(call_i_i661_reload),
    .din165(call_i_i665_reload),
    .din166(call_i_i669_reload),
    .din167(call_i_i673_reload),
    .din168(call_i_i677_reload),
    .din169(call_i_i681_reload),
    .din170(call_i_i685_reload),
    .din171(call_i_i689_reload),
    .din172(call_i_i693_reload),
    .din173(call_i_i697_reload),
    .din174(call_i_i701_reload),
    .din175(call_i_i705_reload),
    .din176(call_i_i709_reload),
    .din177(call_i_i713_reload),
    .din178(call_i_i717_reload),
    .din179(call_i_i721_reload),
    .din180(call_i_i725_reload),
    .din181(call_i_i729_reload),
    .din182(call_i_i733_reload),
    .din183(call_i_i737_reload),
    .din184(call_i_i741_reload),
    .din185(call_i_i745_reload),
    .din186(call_i_i749_reload),
    .din187(call_i_i753_reload),
    .din188(call_i_i757_reload),
    .din189(call_i_i761_reload),
    .din190(call_i_i765_reload),
    .din191(call_i_i769_reload),
    .din192(call_i_i773_reload),
    .din193(call_i_i777_reload),
    .din194(call_i_i781_reload),
    .din195(call_i_i785_reload),
    .din196(call_i_i789_reload),
    .din197(call_i_i793_reload),
    .din198(call_i_i797_reload),
    .din199(call_i_i801_reload),
    .din200(call_i_i805_reload),
    .din201(call_i_i809_reload),
    .din202(call_i_i813_reload),
    .din203(call_i_i817_reload),
    .din204(call_i_i821_reload),
    .din205(call_i_i825_reload),
    .din206(call_i_i829_reload),
    .din207(call_i_i833_reload),
    .din208(call_i_i837_reload),
    .din209(call_i_i841_reload),
    .din210(call_i_i845_reload),
    .din211(call_i_i849_reload),
    .din212(call_i_i853_reload),
    .din213(call_i_i857_reload),
    .din214(call_i_i861_reload),
    .din215(call_i_i865_reload),
    .din216(call_i_i869_reload),
    .din217(call_i_i873_reload),
    .din218(call_i_i877_reload),
    .din219(call_i_i881_reload),
    .din220(call_i_i885_reload),
    .din221(call_i_i889_reload),
    .din222(call_i_i893_reload),
    .din223(call_i_i897_reload),
    .din224(call_i_i901_reload),
    .din225(call_i_i905_reload),
    .din226(call_i_i909_reload),
    .din227(call_i_i913_reload),
    .din228(call_i_i917_reload),
    .din229(call_i_i921_reload),
    .din230(call_i_i925_reload),
    .din231(call_i_i929_reload),
    .din232(call_i_i933_reload),
    .din233(call_i_i937_reload),
    .din234(call_i_i941_reload),
    .din235(call_i_i945_reload),
    .din236(call_i_i949_reload),
    .din237(call_i_i953_reload),
    .din238(call_i_i957_reload),
    .din239(call_i_i961_reload),
    .din240(call_i_i965_reload),
    .din241(ap_sig_allocacmp_i_1),
    .dout(val_fu_2037_p243)
);

stereolbm_accel_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln249_fu_2019_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_554 <= add_ln249_fu_2025_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_554 <= 8'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln249_fu_2019_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        pixelpacket_data_V_reg_2800 <= pixelpacket_data_V_fu_2765_p3;
        tmp_V_reg_2795 <= tmp_V_fu_2031_p2;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        AXI_Laser_blk_n = AXI_Laser_full_n;
    end else begin
        AXI_Laser_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        AXI_Laser_write = 1'b1;
    end else begin
        AXI_Laser_write = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln249_fu_2019_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_start_int == 1'b0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_loop_init == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1 = 8'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_554;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign AXI_Laser_din = {{tmp_V_reg_2795}, {pixelpacket_data_V_reg_2800}};

assign add_ln249_fu_2025_p2 = (ap_sig_allocacmp_i_1 + 8'd1);

assign and_ln299_fu_2745_p2 = (xor_ln295_fu_2739_p2 & icmp_ln299_fu_2591_p2);

assign and_ln301_fu_2667_p2 = (xor_ln299_fu_2661_p2 & icmp_ln301_fu_2597_p2);

assign and_ln302_1_fu_2719_p2 = (xor_ln302_fu_2713_p2 & and_ln301_fu_2667_p2);

assign and_ln302_fu_2673_p2 = (icmp_ln302_fu_2603_p2 & and_ln301_fu_2667_p2);

assign and_ln320_fu_2699_p2 = (xor_ln301_fu_2693_p2 & icmp_ln320_fu_2625_p2);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((1'b0 == AXI_Laser_full_n) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((1'b0 == AXI_Laser_full_n) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == AXI_Laser_full_n) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (1'b0 == AXI_Laser_full_n);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign exp_fu_2541_p4 = {{reg_fu_2525_p1[30:23]}};

assign icmp_ln249_fu_2019_p2 = ((ap_sig_allocacmp_i_1 == 8'd241) ? 1'b1 : 1'b0);

assign icmp_ln295_fu_2571_p2 = ((trunc_ln278_fu_2529_p1 == 31'd0) ? 1'b1 : 1'b0);

assign icmp_ln299_fu_2591_p2 = ((exp_fu_2541_p4 == 8'd150) ? 1'b1 : 1'b0);

assign icmp_ln301_fu_2597_p2 = (($signed(sh_amt_fu_2577_p2) > $signed(9'd0)) ? 1'b1 : 1'b0);

assign icmp_ln302_fu_2603_p2 = (($signed(sh_amt_fu_2577_p2) < $signed(9'd25)) ? 1'b1 : 1'b0);

assign icmp_ln320_fu_2625_p2 = ((tmp_fu_2615_p4 == 4'd0) ? 1'b1 : 1'b0);

assign lshr_ln304_fu_2635_p2 = zext_ln304_fu_2631_p1 >> sext_ln298_fu_2587_p1;

assign or_ln299_fu_2655_p2 = (icmp_ln299_fu_2591_p2 | icmp_ln295_fu_2571_p2);

assign or_ln301_fu_2687_p2 = (or_ln299_fu_2655_p2 | icmp_ln301_fu_2597_p2);

assign or_ln302_fu_2725_p2 = (icmp_ln295_fu_2571_p2 | and_ln302_1_fu_2719_p2);

assign p_Result_s_fu_2533_p3 = reg_fu_2525_p1[32'd31];

assign pixelpacket_data_V_fu_2765_p3 = ((p_Result_s_fu_2533_p3[0:0] == 1'b1) ? sub_ln501_fu_2759_p2 : select_ln299_fu_2751_p3);

assign reg_fu_2525_p1 = val_fu_2037_p243;

assign select_ln299_fu_2751_p3 = ((and_ln299_fu_2745_p2[0:0] == 1'b1) ? trunc_ln300_fu_2559_p1 : select_ln302_1_fu_2731_p3);

assign select_ln302_1_fu_2731_p3 = ((or_ln302_fu_2725_p2[0:0] == 1'b1) ? 8'd0 : select_ln320_fu_2705_p3);

assign select_ln302_fu_2679_p3 = ((and_ln302_fu_2673_p2[0:0] == 1'b1) ? trunc_ln311_fu_2641_p1 : 8'd0);

assign select_ln320_fu_2705_p3 = ((and_ln320_fu_2699_p2[0:0] == 1'b1) ? shl_ln322_fu_2649_p2 : select_ln302_fu_2679_p3);

assign sext_ln298_fu_2587_p1 = sh_amt_fu_2577_p2;

assign sh_amt_1_fu_2609_p2 = (7'd0 - trunc_ln298_fu_2583_p1);

assign sh_amt_1cast_fu_2645_p1 = sh_amt_1_fu_2609_p2;

assign sh_amt_fu_2577_p2 = (9'd150 - zext_ln283_fu_2551_p1);

assign shl_ln322_fu_2649_p2 = trunc_ln300_fu_2559_p1 << sh_amt_1cast_fu_2645_p1;

assign sub_ln501_fu_2759_p2 = (8'd0 - select_ln299_fu_2751_p3);

assign tmp_4_fu_2563_p3 = {{1'd1}, {trunc_ln287_fu_2555_p1}};

assign tmp_V_fu_2031_p2 = ((ap_sig_allocacmp_i_1 == 8'd240) ? 1'b1 : 1'b0);

assign tmp_fu_2615_p4 = {{sh_amt_1_fu_2609_p2[6:3]}};

assign trunc_ln278_fu_2529_p1 = reg_fu_2525_p1[30:0];

assign trunc_ln287_fu_2555_p1 = reg_fu_2525_p1[22:0];

assign trunc_ln298_fu_2583_p1 = sh_amt_fu_2577_p2[6:0];

assign trunc_ln300_fu_2559_p1 = reg_fu_2525_p1[7:0];

assign trunc_ln311_fu_2641_p1 = lshr_ln304_fu_2635_p2[7:0];

assign xor_ln295_fu_2739_p2 = (icmp_ln295_fu_2571_p2 ^ 1'd1);

assign xor_ln299_fu_2661_p2 = (or_ln299_fu_2655_p2 ^ 1'd1);

assign xor_ln301_fu_2693_p2 = (or_ln301_fu_2687_p2 ^ 1'd1);

assign xor_ln302_fu_2713_p2 = (icmp_ln302_fu_2603_p2 ^ 1'd1);

assign zext_ln283_fu_2551_p1 = exp_fu_2541_p4;

assign zext_ln304_fu_2631_p1 = tmp_4_fu_2563_p3;

endmodule //stereolbm_accel_xfMat2AXILaser_1_720_1280_1_Pipeline_loop_ls_2axi
