// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module stereolbm_accel_xFReadOutStream_720_1280_1_3_0_2_1280_s (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        in_sobel_y_i4_42_dout,
        in_sobel_y_i4_42_empty_n,
        in_sobel_y_i4_42_read,
        height_dout,
        height_empty_n,
        height_read,
        width_dout,
        width_empty_n,
        width_read
);

parameter    ap_ST_fsm_state1 = 3'd1;
parameter    ap_ST_fsm_state2 = 3'd2;
parameter    ap_ST_fsm_state3 = 3'd4;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
input  [15:0] in_sobel_y_i4_42_dout;
input   in_sobel_y_i4_42_empty_n;
output   in_sobel_y_i4_42_read;
input  [9:0] height_dout;
input   height_empty_n;
output   height_read;
input  [10:0] width_dout;
input   width_empty_n;
output   width_read;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg in_sobel_y_i4_42_read;
reg height_read;
reg width_read;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [2:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
reg    height_blk_n;
reg    width_blk_n;
reg   [10:0] width_read_reg_100;
reg   [9:0] height_read_reg_105;
wire    grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_ap_start;
wire    grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_ap_done;
wire    grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_ap_idle;
wire    grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_ap_ready;
wire    grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_in_sobel_y_i4_42_read;
reg    grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_ap_start_reg;
wire    ap_CS_fsm_state2;
wire   [0:0] icmp_ln650_fu_77_p2;
wire    ap_CS_fsm_state3;
reg   [9:0] i_04_fu_46;
wire   [9:0] i_5_fu_82_p2;
reg    ap_block_state1;
reg   [2:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_ST_fsm_state2_blk;
reg    ap_ST_fsm_state3_blk;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 3'd1;
#0 grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_ap_start_reg = 1'b0;
end

stereolbm_accel_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_ap_start),
    .ap_done(grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_ap_done),
    .ap_idle(grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_ap_idle),
    .ap_ready(grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_ap_ready),
    .in_sobel_y_i4_42_dout(in_sobel_y_i4_42_dout),
    .in_sobel_y_i4_42_empty_n(in_sobel_y_i4_42_empty_n),
    .in_sobel_y_i4_42_read(grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_in_sobel_y_i4_42_read),
    .width_load(width_read_reg_100)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((icmp_ln650_fu_77_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_ap_start_reg <= 1'b0;
    end else begin
        if (((icmp_ln650_fu_77_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
            grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_ap_start_reg <= 1'b1;
        end else if ((grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_ap_ready == 1'b1)) begin
            grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((~((ap_start == 1'b0) | (width_empty_n == 1'b0) | (height_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_04_fu_46 <= 10'd0;
    end else if (((icmp_ln650_fu_77_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        i_04_fu_46 <= i_5_fu_82_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state1)) begin
        height_read_reg_105 <= height_dout;
        width_read_reg_100 <= width_dout;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) | (width_empty_n == 1'b0) | (height_empty_n == 1'b0) | (ap_done_reg == 1'b1))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

assign ap_ST_fsm_state2_blk = 1'b0;

always @ (*) begin
    if ((grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_ap_done == 1'b0)) begin
        ap_ST_fsm_state3_blk = 1'b1;
    end else begin
        ap_ST_fsm_state3_blk = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln650_fu_77_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln650_fu_77_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_blk_n = height_empty_n;
    end else begin
        height_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (width_empty_n == 1'b0) | (height_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        height_read = 1'b1;
    end else begin
        height_read = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state3)) begin
        in_sobel_y_i4_42_read = grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_in_sobel_y_i4_42_read;
    end else begin
        in_sobel_y_i4_42_read = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_blk_n = width_empty_n;
    end else begin
        width_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start == 1'b0) | (width_empty_n == 1'b0) | (height_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        width_read = 1'b1;
    end else begin
        width_read = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (width_empty_n == 1'b0) | (height_empty_n == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((icmp_ln650_fu_77_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            if (((grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_ap_done == 1'b1) & (1'b1 == ap_CS_fsm_state3))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (width_empty_n == 1'b0) | (height_empty_n == 1'b0) | (ap_done_reg == 1'b1));
end

assign grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_ap_start = grp_xFReadOutStream_720_1280_1_3_0_2_1280_Pipeline_loop_col_clip_fu_62_ap_start_reg;

assign i_5_fu_82_p2 = (i_04_fu_46 + 10'd1);

assign icmp_ln650_fu_77_p2 = ((i_04_fu_46 == height_read_reg_105) ? 1'b1 : 1'b0);

endmodule //stereolbm_accel_xFReadOutStream_720_1280_1_3_0_2_1280_s
