// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2021.2 (64-bit)
// Version: 2021.2
// Copyright (C) Copyright 1986-2021 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module stereolbm_accel_atan2_cordic_float_s (
        ap_clk,
        ap_rst,
        y_in,
        x_in,
        ap_return,
        ap_ce
);


input   ap_clk;
input   ap_rst;
input  [31:0] y_in;
input  [31:0] x_in;
output  [31:0] ap_return;
input   ap_ce;

reg[31:0] ap_return;

reg   [31:0] c_reg_88;
reg   [31:0] c_reg_88_pp0_iter21_reg;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_state3_pp0_stage0_iter2;
wire    ap_block_state4_pp0_stage0_iter3;
wire    ap_block_state5_pp0_stage0_iter4;
wire    ap_block_state6_pp0_stage0_iter5;
wire    ap_block_state7_pp0_stage0_iter6;
wire    ap_block_state8_pp0_stage0_iter7;
wire    ap_block_state9_pp0_stage0_iter8;
wire    ap_block_state10_pp0_stage0_iter9;
wire    ap_block_state11_pp0_stage0_iter10;
wire    ap_block_state12_pp0_stage0_iter11;
wire    ap_block_state13_pp0_stage0_iter12;
wire    ap_block_state14_pp0_stage0_iter13;
wire    ap_block_state15_pp0_stage0_iter14;
wire    ap_block_state16_pp0_stage0_iter15;
wire    ap_block_state17_pp0_stage0_iter16;
wire    ap_block_state18_pp0_stage0_iter17;
wire    ap_block_state19_pp0_stage0_iter18;
wire    ap_block_state20_pp0_stage0_iter19;
wire    ap_block_state21_pp0_stage0_iter20;
wire    ap_block_state22_pp0_stage0_iter21;
wire    ap_block_state23_pp0_stage0_iter22;
wire    ap_block_state24_pp0_stage0_iter23;
wire    ap_block_state25_pp0_stage0_iter24;
wire    ap_block_pp0_stage0_11001;
reg   [31:0] c_reg_88_pp0_iter22_reg;
wire   [31:0] grp_atan2_generic_float_s_fu_166_ap_return;
reg   [31:0] reg_187;
reg   [0:0] or_ln757_reg_558;
reg   [0:0] or_ln757_reg_558_pp0_iter14_reg;
reg   [0:0] or_ln757_1_reg_567;
reg   [0:0] or_ln757_1_reg_567_pp0_iter14_reg;
reg   [0:0] icmp_ln1018_reg_571;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter14_reg;
reg   [0:0] icmp_ln766_reg_583;
reg   [0:0] icmp_ln766_reg_583_pp0_iter14_reg;
reg   [0:0] icmp_ln1018_4_reg_579;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter14_reg;
reg   [0:0] and_ln18_reg_587;
reg   [0:0] and_ln18_reg_587_pp0_iter14_reg;
reg   [0:0] and_ln18_2_reg_591;
reg   [0:0] and_ln18_2_reg_591_pp0_iter14_reg;
reg   [0:0] icmp_ln1018_5_reg_609;
reg   [0:0] icmp_ln1018_5_reg_609_pp0_iter14_reg;
reg   [0:0] and_ln746_1_reg_623;
reg   [0:0] and_ln746_1_reg_623_pp0_iter14_reg;
wire   [0:0] p_Result_s_fu_197_p3;
reg   [0:0] p_Result_s_reg_536;
reg   [0:0] p_Result_s_reg_536_pp0_iter1_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter2_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter3_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter4_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter5_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter6_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter7_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter8_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter9_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter10_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter11_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter12_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter13_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter14_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter15_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter16_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter17_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter18_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter19_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter20_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter21_reg;
reg   [0:0] p_Result_s_reg_536_pp0_iter22_reg;
reg   [0:0] p_Result_14_reg_541;
reg   [0:0] p_Result_14_reg_541_pp0_iter1_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter2_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter3_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter4_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter5_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter6_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter7_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter8_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter9_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter10_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter11_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter12_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter13_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter14_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter15_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter16_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter17_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter18_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter19_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter20_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter21_reg;
reg   [0:0] p_Result_14_reg_541_pp0_iter22_reg;
wire   [0:0] icmp_ln1022_fu_257_p2;
reg   [0:0] icmp_ln1022_reg_553;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter1_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter2_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter3_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter4_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter5_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter6_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter7_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter8_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter9_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter10_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter11_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter12_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter13_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter14_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter15_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter16_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter17_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter18_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter19_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter20_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter21_reg;
reg   [0:0] icmp_ln1022_reg_553_pp0_iter22_reg;
wire   [0:0] or_ln757_fu_263_p2;
reg   [0:0] or_ln757_reg_558_pp0_iter1_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter2_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter3_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter4_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter5_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter6_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter7_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter8_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter9_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter10_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter11_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter12_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter13_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter15_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter16_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter17_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter18_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter19_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter20_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter21_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter22_reg;
reg   [0:0] or_ln757_reg_558_pp0_iter23_reg;
wire   [0:0] icmp_ln1022_1_fu_281_p2;
reg   [0:0] icmp_ln1022_1_reg_562;
wire   [0:0] or_ln757_1_fu_287_p2;
reg   [0:0] or_ln757_1_reg_567_pp0_iter1_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter2_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter3_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter4_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter5_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter6_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter7_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter8_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter9_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter10_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter11_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter12_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter13_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter15_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter16_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter17_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter18_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter19_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter20_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter21_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter22_reg;
reg   [0:0] or_ln757_1_reg_567_pp0_iter23_reg;
wire   [0:0] icmp_ln1018_fu_293_p2;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter1_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter2_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter3_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter4_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter5_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter6_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter7_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter8_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter9_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter10_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter11_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter12_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter13_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter15_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter16_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter17_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter18_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter19_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter20_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter21_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter22_reg;
reg   [0:0] icmp_ln1018_reg_571_pp0_iter23_reg;
wire   [0:0] and_ln762_fu_299_p2;
reg   [0:0] and_ln762_reg_575;
reg   [0:0] and_ln762_reg_575_pp0_iter1_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter2_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter3_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter4_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter5_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter6_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter7_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter8_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter9_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter10_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter11_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter12_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter13_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter14_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter15_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter16_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter17_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter18_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter19_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter20_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter21_reg;
reg   [0:0] and_ln762_reg_575_pp0_iter22_reg;
wire   [0:0] icmp_ln1018_4_fu_305_p2;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter1_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter2_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter3_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter4_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter5_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter6_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter7_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter8_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter9_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter10_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter11_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter12_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter13_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter15_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter16_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter17_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter18_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter19_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter20_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter21_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter22_reg;
reg   [0:0] icmp_ln1018_4_reg_579_pp0_iter23_reg;
wire   [0:0] icmp_ln766_fu_339_p2;
reg   [0:0] icmp_ln766_reg_583_pp0_iter1_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter2_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter3_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter4_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter5_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter6_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter7_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter8_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter9_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter10_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter11_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter12_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter13_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter15_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter16_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter17_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter18_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter19_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter20_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter21_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter22_reg;
reg   [0:0] icmp_ln766_reg_583_pp0_iter23_reg;
wire   [0:0] and_ln18_fu_345_p2;
reg   [0:0] and_ln18_reg_587_pp0_iter1_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter2_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter3_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter4_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter5_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter6_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter7_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter8_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter9_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter10_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter11_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter12_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter13_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter15_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter16_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter17_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter18_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter19_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter20_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter21_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter22_reg;
reg   [0:0] and_ln18_reg_587_pp0_iter23_reg;
wire   [0:0] and_ln18_2_fu_351_p2;
reg   [0:0] and_ln18_2_reg_591_pp0_iter1_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter2_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter3_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter4_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter5_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter6_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter7_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter8_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter9_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter10_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter11_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter12_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter13_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter15_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter16_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter17_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter18_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter19_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter20_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter21_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter22_reg;
reg   [0:0] and_ln18_2_reg_591_pp0_iter23_reg;
wire   [31:0] a_fu_369_p1;
reg   [31:0] a_reg_595;
reg   [31:0] a_reg_595_pp0_iter1_reg;
wire   [31:0] b_fu_386_p1;
reg   [31:0] b_reg_602;
reg   [31:0] b_reg_602_pp0_iter1_reg;
wire   [0:0] icmp_ln1018_5_fu_391_p2;
reg   [0:0] icmp_ln1018_5_reg_609_pp0_iter1_reg;
reg   [0:0] icmp_ln1018_5_reg_609_pp0_iter2_reg;
reg   [0:0] icmp_ln1018_5_reg_609_pp0_iter3_reg;
reg   [0:0] icmp_ln1018_5_reg_609_pp0_iter4_reg;
reg   [0:0] icmp_ln1018_5_reg_609_pp0_iter5_reg;
reg   [0:0] icmp_ln1018_5_reg_609_pp0_iter6_reg;
reg   [0:0] icmp_ln1018_5_reg_609_pp0_iter7_reg;
reg   [0:0] icmp_ln1018_5_reg_609_pp0_iter8_reg;
reg   [0:0] icmp_ln1018_5_reg_609_pp0_iter9_reg;
reg   [0:0] icmp_ln1018_5_reg_609_pp0_iter10_reg;
reg   [0:0] icmp_ln1018_5_reg_609_pp0_iter11_reg;
reg   [0:0] icmp_ln1018_5_reg_609_pp0_iter12_reg;
reg   [0:0] icmp_ln1018_5_reg_609_pp0_iter13_reg;
reg   [0:0] icmp_ln1018_5_reg_609_pp0_iter15_reg;
reg   [0:0] icmp_ln1018_5_reg_609_pp0_iter16_reg;
reg   [0:0] icmp_ln1018_5_reg_609_pp0_iter17_reg;
reg   [0:0] icmp_ln1018_5_reg_609_pp0_iter18_reg;
wire   [0:0] icmp_ln746_fu_397_p2;
reg   [0:0] icmp_ln746_reg_613;
wire   [0:0] icmp_ln746_1_fu_403_p2;
reg   [0:0] icmp_ln746_1_reg_618;
wire   [0:0] and_ln746_1_fu_423_p2;
reg   [0:0] and_ln746_1_reg_623_pp0_iter2_reg;
reg   [0:0] and_ln746_1_reg_623_pp0_iter3_reg;
reg   [0:0] and_ln746_1_reg_623_pp0_iter4_reg;
reg   [0:0] and_ln746_1_reg_623_pp0_iter5_reg;
reg   [0:0] and_ln746_1_reg_623_pp0_iter6_reg;
reg   [0:0] and_ln746_1_reg_623_pp0_iter7_reg;
reg   [0:0] and_ln746_1_reg_623_pp0_iter8_reg;
reg   [0:0] and_ln746_1_reg_623_pp0_iter9_reg;
reg   [0:0] and_ln746_1_reg_623_pp0_iter10_reg;
reg   [0:0] and_ln746_1_reg_623_pp0_iter11_reg;
reg   [0:0] and_ln746_1_reg_623_pp0_iter12_reg;
reg   [0:0] and_ln746_1_reg_623_pp0_iter13_reg;
reg   [0:0] and_ln746_1_reg_623_pp0_iter15_reg;
reg   [0:0] and_ln746_1_reg_623_pp0_iter16_reg;
reg   [0:0] and_ln746_1_reg_623_pp0_iter17_reg;
reg   [0:0] and_ln746_1_reg_623_pp0_iter18_reg;
wire   [31:0] grp_fu_172_p2;
wire   [1:0] tmp_3_fu_429_p3;
reg   [1:0] tmp_3_reg_632;
reg   [1:0] tmp_3_reg_632_pp0_iter21_reg;
reg   [1:0] tmp_3_reg_632_pp0_iter22_reg;
reg   [1:0] tmp_3_reg_632_pp0_iter23_reg;
wire   [31:0] grp_fu_177_p2;
reg   [31:0] d_reg_636;
wire   [31:0] bitcast_ln822_1_fu_445_p1;
wire   [31:0] select_ln809_fu_449_p3;
wire   [31:0] bitcast_ln354_5_fu_463_p1;
wire   [31:0] bitcast_ln354_4_fu_474_p1;
wire   [31:0] bitcast_ln354_3_fu_485_p1;
wire   [31:0] bitcast_ln354_2_fu_496_p1;
wire   [31:0] bitcast_ln354_1_fu_507_p1;
wire   [31:0] bitcast_ln354_fu_518_p1;
reg   [31:0] grp_atan2_generic_float_s_fu_166_y_in;
reg   [31:0] grp_atan2_generic_float_s_fu_166_x_in;
reg    grp_atan2_generic_float_s_fu_166_ap_ce;
reg    ap_predicate_op84_call_state3;
reg    ap_predicate_op85_call_state3;
wire    ap_block_state1_pp0_stage0_iter0_ignore_call0;
wire    ap_block_state2_pp0_stage0_iter1_ignore_call0;
wire    ap_block_state3_pp0_stage0_iter2_ignore_call0;
wire    ap_block_state4_pp0_stage0_iter3_ignore_call0;
wire    ap_block_state5_pp0_stage0_iter4_ignore_call0;
wire    ap_block_state6_pp0_stage0_iter5_ignore_call0;
wire    ap_block_state7_pp0_stage0_iter6_ignore_call0;
wire    ap_block_state8_pp0_stage0_iter7_ignore_call0;
wire    ap_block_state9_pp0_stage0_iter8_ignore_call0;
wire    ap_block_state10_pp0_stage0_iter9_ignore_call0;
wire    ap_block_state11_pp0_stage0_iter10_ignore_call0;
wire    ap_block_state12_pp0_stage0_iter11_ignore_call0;
wire    ap_block_state13_pp0_stage0_iter12_ignore_call0;
wire    ap_block_state14_pp0_stage0_iter13_ignore_call0;
wire    ap_block_state15_pp0_stage0_iter14_ignore_call0;
wire    ap_block_state16_pp0_stage0_iter15_ignore_call0;
wire    ap_block_state17_pp0_stage0_iter16_ignore_call0;
wire    ap_block_state18_pp0_stage0_iter17_ignore_call0;
wire    ap_block_state19_pp0_stage0_iter18_ignore_call0;
wire    ap_block_state20_pp0_stage0_iter19_ignore_call0;
wire    ap_block_state21_pp0_stage0_iter20_ignore_call0;
wire    ap_block_state22_pp0_stage0_iter21_ignore_call0;
wire    ap_block_state23_pp0_stage0_iter22_ignore_call0;
wire    ap_block_state24_pp0_stage0_iter23_ignore_call0;
wire    ap_block_state25_pp0_stage0_iter24_ignore_call0;
wire    ap_block_pp0_stage0_11001_ignoreCallOp84;
wire   [31:0] ap_phi_reg_pp0_iter0_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter1_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter2_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter3_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter4_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter5_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter6_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter7_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter8_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter9_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter10_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter11_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter12_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter13_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter14_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter15_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter16_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter17_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter18_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter19_c_reg_88;
reg   [31:0] ap_phi_reg_pp0_iter20_c_reg_88;
reg   [31:0] ap_phi_mux_UnifiedRetVal_phi_fu_114_p40;
wire   [31:0] ap_phi_reg_pp0_iter0_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter1_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter2_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter3_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter4_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter5_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter6_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter7_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter8_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter9_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter10_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter11_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter12_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter13_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter14_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter15_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter16_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter18_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter19_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter20_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter21_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter22_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter23_UnifiedRetVal_reg_102;
reg   [31:0] ap_phi_reg_pp0_iter24_UnifiedRetVal_reg_102;
wire   [31:0] bitcast_ln826_1_fu_531_p1;
wire    ap_block_pp0_stage0;
wire   [31:0] grp_fu_183_p0;
wire   [31:0] grp_fu_183_p1;
wire   [31:0] data_V_fu_193_p1;
wire   [31:0] data_V_4_fu_219_p1;
wire   [7:0] tmp_459_fu_231_p4;
wire   [0:0] icmp_ln757_fu_245_p2;
wire   [22:0] tmp_460_fu_241_p1;
wire   [0:0] xor_ln18_fu_251_p2;
wire   [7:0] tmp_fu_205_p4;
wire   [0:0] icmp_ln757_1_fu_269_p2;
wire   [22:0] tmp_458_fu_215_p1;
wire   [0:0] xor_ln18_1_fu_275_p2;
wire   [7:0] trunc_ln766_fu_311_p1;
wire   [14:0] tmp_1_fu_321_p4;
wire   [7:0] or_ln766_fu_315_p2;
wire   [22:0] tmp_2_fu_331_p3;
wire   [30:0] trunc_ln368_fu_357_p1;
wire   [31:0] p_Result_21_fu_361_p3;
wire   [30:0] trunc_ln368_1_fu_374_p1;
wire   [31:0] p_Result_22_fu_378_p3;
wire   [0:0] or_ln746_fu_409_p2;
wire   [0:0] or_ln746_1_fu_413_p2;
wire   [0:0] and_ln746_fu_417_p2;
wire   [0:0] grp_fu_183_p2;
wire   [31:0] bitcast_ln822_fu_435_p1;
wire   [31:0] xor_ln822_fu_439_p2;
wire   [31:0] p_Result_20_fu_456_p3;
wire   [31:0] p_Result_19_fu_467_p3;
wire   [31:0] p_Result_18_fu_478_p3;
wire   [31:0] p_Result_17_fu_489_p3;
wire   [31:0] p_Result_16_fu_500_p3;
wire   [31:0] p_Result_15_fu_511_p3;
wire   [31:0] bitcast_ln826_fu_522_p1;
wire   [31:0] xor_ln826_fu_525_p2;
reg    grp_fu_172_ce;
reg    grp_fu_177_ce;
reg    grp_fu_183_ce;
reg    ap_predicate_op75_fcmp_state1;
wire    ap_block_pp0_stage0_00001;
reg    ap_ce_reg;
reg   [31:0] y_in_int_reg;
reg   [31:0] x_in_int_reg;
reg   [31:0] ap_return_int_reg;
reg    ap_condition_89;
reg    ap_condition_981;
reg    ap_condition_507;
reg    ap_condition_1016;
reg    ap_condition_1021;
reg    ap_condition_1025;
reg    ap_condition_1030;
reg    ap_condition_1033;
reg    ap_condition_1036;
reg    ap_condition_1063;
reg    ap_condition_1065;
reg    ap_condition_1068;
reg    ap_condition_1056;
reg    ap_condition_545;
reg    ap_condition_550;
reg    ap_condition_591;
reg    ap_condition_586;
reg    ap_condition_581;
reg    ap_condition_572;
reg    ap_condition_567;
reg    ap_condition_555;

stereolbm_accel_atan2_generic_float_s grp_atan2_generic_float_s_fu_166(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .y_in(grp_atan2_generic_float_s_fu_166_y_in),
    .x_in(grp_atan2_generic_float_s_fu_166_x_in),
    .ap_return(grp_atan2_generic_float_s_fu_166_ap_return),
    .ap_ce(grp_atan2_generic_float_s_fu_166_ap_ce)
);

stereolbm_accel_fsub_32ns_32ns_32_4_full_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_4_full_dsp_0_U478(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1070141403),
    .din1(reg_187),
    .ce(grp_fu_172_ce),
    .dout(grp_fu_172_p2)
);

stereolbm_accel_fsub_32ns_32ns_32_4_full_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 4 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 32 ))
fsub_32ns_32ns_32_4_full_dsp_0_U479(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(32'd1078530011),
    .din1(ap_phi_reg_pp0_iter20_c_reg_88),
    .ce(grp_fu_177_ce),
    .dout(grp_fu_177_p2)
);

stereolbm_accel_fcmp_32ns_32ns_1_2_no_dsp_0 #(
    .ID( 1 ),
    .NUM_STAGE( 2 ),
    .din0_WIDTH( 32 ),
    .din1_WIDTH( 32 ),
    .dout_WIDTH( 1 ))
fcmp_32ns_32ns_1_2_no_dsp_0_U480(
    .clk(ap_clk),
    .reset(ap_rst),
    .din0(grp_fu_183_p0),
    .din1(grp_fu_183_p1),
    .ce(grp_fu_183_ce),
    .opcode(5'd2),
    .dout(grp_fu_183_p2)
);

always @ (posedge ap_clk) begin
    ap_ce_reg <= ap_ce;
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((1'b1 == ap_condition_89)) begin
            ap_phi_reg_pp0_iter16_c_reg_88 <= grp_atan2_generic_float_s_fu_166_ap_return;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter16_c_reg_88 <= ap_phi_reg_pp0_iter15_c_reg_88;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if (((or_ln757_1_fu_287_p2 == 1'd0) | (or_ln757_fu_263_p2 == 1'd0))) begin
            ap_phi_reg_pp0_iter1_UnifiedRetVal_reg_102 <= 32'd2147483647;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter0_UnifiedRetVal_reg_102;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((1'b1 == ap_condition_981)) begin
            ap_phi_reg_pp0_iter1_c_reg_88 <= 32'd1061752795;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter1_c_reg_88 <= ap_phi_reg_pp0_iter0_c_reg_88;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((1'b1 == ap_condition_507)) begin
            ap_phi_reg_pp0_iter20_c_reg_88 <= grp_fu_172_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter20_c_reg_88 <= ap_phi_reg_pp0_iter19_c_reg_88;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((1'b1 == ap_condition_1068)) begin
            ap_phi_reg_pp0_iter21_UnifiedRetVal_reg_102 <= 32'd0;
        end else if ((1'b1 == ap_condition_1065)) begin
            ap_phi_reg_pp0_iter21_UnifiedRetVal_reg_102 <= 32'd1061752795;
        end else if ((1'b1 == ap_condition_1063)) begin
            ap_phi_reg_pp0_iter21_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter20_c_reg_88;
        end else if ((1'b1 == ap_condition_1036)) begin
            ap_phi_reg_pp0_iter21_UnifiedRetVal_reg_102 <= 32'd2147483648;
        end else if ((1'b1 == ap_condition_1033)) begin
            ap_phi_reg_pp0_iter21_UnifiedRetVal_reg_102 <= 32'd1078530011;
        end else if ((1'b1 == ap_condition_1030)) begin
            ap_phi_reg_pp0_iter21_UnifiedRetVal_reg_102 <= 32'd3226013659;
        end else if ((1'b1 == ap_condition_1025)) begin
            ap_phi_reg_pp0_iter21_UnifiedRetVal_reg_102 <= 32'd3209236443;
        end else if ((1'b1 == ap_condition_1021)) begin
            ap_phi_reg_pp0_iter21_UnifiedRetVal_reg_102 <= 32'd1075235812;
        end else if ((1'b1 == ap_condition_1016)) begin
            ap_phi_reg_pp0_iter21_UnifiedRetVal_reg_102 <= 32'd3222719460;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter21_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter20_UnifiedRetVal_reg_102;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        if ((1'b1 == ap_condition_555)) begin
            ap_phi_reg_pp0_iter24_UnifiedRetVal_reg_102 <= bitcast_ln354_5_fu_463_p1;
        end else if ((1'b1 == ap_condition_567)) begin
            ap_phi_reg_pp0_iter24_UnifiedRetVal_reg_102 <= bitcast_ln354_4_fu_474_p1;
        end else if ((1'b1 == ap_condition_572)) begin
            ap_phi_reg_pp0_iter24_UnifiedRetVal_reg_102 <= bitcast_ln354_3_fu_485_p1;
        end else if ((1'b1 == ap_condition_581)) begin
            ap_phi_reg_pp0_iter24_UnifiedRetVal_reg_102 <= bitcast_ln354_2_fu_496_p1;
        end else if ((1'b1 == ap_condition_586)) begin
            ap_phi_reg_pp0_iter24_UnifiedRetVal_reg_102 <= bitcast_ln354_1_fu_507_p1;
        end else if ((1'b1 == ap_condition_591)) begin
            ap_phi_reg_pp0_iter24_UnifiedRetVal_reg_102 <= bitcast_ln354_fu_518_p1;
        end else if ((1'b1 == ap_condition_550)) begin
            ap_phi_reg_pp0_iter24_UnifiedRetVal_reg_102 <= select_ln809_fu_449_p3;
        end else if ((1'b1 == ap_condition_545)) begin
            ap_phi_reg_pp0_iter24_UnifiedRetVal_reg_102 <= bitcast_ln822_1_fu_445_p1;
        end else if ((1'b1 == ap_condition_1056)) begin
            ap_phi_reg_pp0_iter24_UnifiedRetVal_reg_102 <= grp_fu_177_p2;
        end else if ((1'b1 == 1'b1)) begin
            ap_phi_reg_pp0_iter24_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter23_UnifiedRetVal_reg_102;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln18_2_fu_351_p2) & (1'd0 == and_ln18_fu_345_p2) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln766_fu_339_p2 == 1'd0) & (icmp_ln1018_4_fu_305_p2 == 1'd0) & (icmp_ln1018_fu_293_p2 == 1'd0) & (or_ln757_1_fu_287_p2 == 1'd1) & (1'b1 == ap_ce_reg) & (or_ln757_fu_263_p2 == 1'd1))) begin
        a_reg_595[30 : 0] <= a_fu_369_p1[30 : 0];
        b_reg_602[30 : 0] <= b_fu_386_p1[30 : 0];
        icmp_ln1018_5_reg_609 <= icmp_ln1018_5_fu_391_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        a_reg_595_pp0_iter1_reg[30 : 0] <= a_reg_595[30 : 0];
        and_ln18_2_reg_591_pp0_iter10_reg <= and_ln18_2_reg_591_pp0_iter9_reg;
        and_ln18_2_reg_591_pp0_iter11_reg <= and_ln18_2_reg_591_pp0_iter10_reg;
        and_ln18_2_reg_591_pp0_iter12_reg <= and_ln18_2_reg_591_pp0_iter11_reg;
        and_ln18_2_reg_591_pp0_iter13_reg <= and_ln18_2_reg_591_pp0_iter12_reg;
        and_ln18_2_reg_591_pp0_iter14_reg <= and_ln18_2_reg_591_pp0_iter13_reg;
        and_ln18_2_reg_591_pp0_iter15_reg <= and_ln18_2_reg_591_pp0_iter14_reg;
        and_ln18_2_reg_591_pp0_iter16_reg <= and_ln18_2_reg_591_pp0_iter15_reg;
        and_ln18_2_reg_591_pp0_iter17_reg <= and_ln18_2_reg_591_pp0_iter16_reg;
        and_ln18_2_reg_591_pp0_iter18_reg <= and_ln18_2_reg_591_pp0_iter17_reg;
        and_ln18_2_reg_591_pp0_iter19_reg <= and_ln18_2_reg_591_pp0_iter18_reg;
        and_ln18_2_reg_591_pp0_iter1_reg <= and_ln18_2_reg_591;
        and_ln18_2_reg_591_pp0_iter20_reg <= and_ln18_2_reg_591_pp0_iter19_reg;
        and_ln18_2_reg_591_pp0_iter21_reg <= and_ln18_2_reg_591_pp0_iter20_reg;
        and_ln18_2_reg_591_pp0_iter22_reg <= and_ln18_2_reg_591_pp0_iter21_reg;
        and_ln18_2_reg_591_pp0_iter23_reg <= and_ln18_2_reg_591_pp0_iter22_reg;
        and_ln18_2_reg_591_pp0_iter2_reg <= and_ln18_2_reg_591_pp0_iter1_reg;
        and_ln18_2_reg_591_pp0_iter3_reg <= and_ln18_2_reg_591_pp0_iter2_reg;
        and_ln18_2_reg_591_pp0_iter4_reg <= and_ln18_2_reg_591_pp0_iter3_reg;
        and_ln18_2_reg_591_pp0_iter5_reg <= and_ln18_2_reg_591_pp0_iter4_reg;
        and_ln18_2_reg_591_pp0_iter6_reg <= and_ln18_2_reg_591_pp0_iter5_reg;
        and_ln18_2_reg_591_pp0_iter7_reg <= and_ln18_2_reg_591_pp0_iter6_reg;
        and_ln18_2_reg_591_pp0_iter8_reg <= and_ln18_2_reg_591_pp0_iter7_reg;
        and_ln18_2_reg_591_pp0_iter9_reg <= and_ln18_2_reg_591_pp0_iter8_reg;
        and_ln18_reg_587_pp0_iter10_reg <= and_ln18_reg_587_pp0_iter9_reg;
        and_ln18_reg_587_pp0_iter11_reg <= and_ln18_reg_587_pp0_iter10_reg;
        and_ln18_reg_587_pp0_iter12_reg <= and_ln18_reg_587_pp0_iter11_reg;
        and_ln18_reg_587_pp0_iter13_reg <= and_ln18_reg_587_pp0_iter12_reg;
        and_ln18_reg_587_pp0_iter14_reg <= and_ln18_reg_587_pp0_iter13_reg;
        and_ln18_reg_587_pp0_iter15_reg <= and_ln18_reg_587_pp0_iter14_reg;
        and_ln18_reg_587_pp0_iter16_reg <= and_ln18_reg_587_pp0_iter15_reg;
        and_ln18_reg_587_pp0_iter17_reg <= and_ln18_reg_587_pp0_iter16_reg;
        and_ln18_reg_587_pp0_iter18_reg <= and_ln18_reg_587_pp0_iter17_reg;
        and_ln18_reg_587_pp0_iter19_reg <= and_ln18_reg_587_pp0_iter18_reg;
        and_ln18_reg_587_pp0_iter1_reg <= and_ln18_reg_587;
        and_ln18_reg_587_pp0_iter20_reg <= and_ln18_reg_587_pp0_iter19_reg;
        and_ln18_reg_587_pp0_iter21_reg <= and_ln18_reg_587_pp0_iter20_reg;
        and_ln18_reg_587_pp0_iter22_reg <= and_ln18_reg_587_pp0_iter21_reg;
        and_ln18_reg_587_pp0_iter23_reg <= and_ln18_reg_587_pp0_iter22_reg;
        and_ln18_reg_587_pp0_iter2_reg <= and_ln18_reg_587_pp0_iter1_reg;
        and_ln18_reg_587_pp0_iter3_reg <= and_ln18_reg_587_pp0_iter2_reg;
        and_ln18_reg_587_pp0_iter4_reg <= and_ln18_reg_587_pp0_iter3_reg;
        and_ln18_reg_587_pp0_iter5_reg <= and_ln18_reg_587_pp0_iter4_reg;
        and_ln18_reg_587_pp0_iter6_reg <= and_ln18_reg_587_pp0_iter5_reg;
        and_ln18_reg_587_pp0_iter7_reg <= and_ln18_reg_587_pp0_iter6_reg;
        and_ln18_reg_587_pp0_iter8_reg <= and_ln18_reg_587_pp0_iter7_reg;
        and_ln18_reg_587_pp0_iter9_reg <= and_ln18_reg_587_pp0_iter8_reg;
        and_ln746_1_reg_623_pp0_iter10_reg <= and_ln746_1_reg_623_pp0_iter9_reg;
        and_ln746_1_reg_623_pp0_iter11_reg <= and_ln746_1_reg_623_pp0_iter10_reg;
        and_ln746_1_reg_623_pp0_iter12_reg <= and_ln746_1_reg_623_pp0_iter11_reg;
        and_ln746_1_reg_623_pp0_iter13_reg <= and_ln746_1_reg_623_pp0_iter12_reg;
        and_ln746_1_reg_623_pp0_iter14_reg <= and_ln746_1_reg_623_pp0_iter13_reg;
        and_ln746_1_reg_623_pp0_iter15_reg <= and_ln746_1_reg_623_pp0_iter14_reg;
        and_ln746_1_reg_623_pp0_iter16_reg <= and_ln746_1_reg_623_pp0_iter15_reg;
        and_ln746_1_reg_623_pp0_iter17_reg <= and_ln746_1_reg_623_pp0_iter16_reg;
        and_ln746_1_reg_623_pp0_iter18_reg <= and_ln746_1_reg_623_pp0_iter17_reg;
        and_ln746_1_reg_623_pp0_iter2_reg <= and_ln746_1_reg_623;
        and_ln746_1_reg_623_pp0_iter3_reg <= and_ln746_1_reg_623_pp0_iter2_reg;
        and_ln746_1_reg_623_pp0_iter4_reg <= and_ln746_1_reg_623_pp0_iter3_reg;
        and_ln746_1_reg_623_pp0_iter5_reg <= and_ln746_1_reg_623_pp0_iter4_reg;
        and_ln746_1_reg_623_pp0_iter6_reg <= and_ln746_1_reg_623_pp0_iter5_reg;
        and_ln746_1_reg_623_pp0_iter7_reg <= and_ln746_1_reg_623_pp0_iter6_reg;
        and_ln746_1_reg_623_pp0_iter8_reg <= and_ln746_1_reg_623_pp0_iter7_reg;
        and_ln746_1_reg_623_pp0_iter9_reg <= and_ln746_1_reg_623_pp0_iter8_reg;
        and_ln762_reg_575_pp0_iter10_reg <= and_ln762_reg_575_pp0_iter9_reg;
        and_ln762_reg_575_pp0_iter11_reg <= and_ln762_reg_575_pp0_iter10_reg;
        and_ln762_reg_575_pp0_iter12_reg <= and_ln762_reg_575_pp0_iter11_reg;
        and_ln762_reg_575_pp0_iter13_reg <= and_ln762_reg_575_pp0_iter12_reg;
        and_ln762_reg_575_pp0_iter14_reg <= and_ln762_reg_575_pp0_iter13_reg;
        and_ln762_reg_575_pp0_iter15_reg <= and_ln762_reg_575_pp0_iter14_reg;
        and_ln762_reg_575_pp0_iter16_reg <= and_ln762_reg_575_pp0_iter15_reg;
        and_ln762_reg_575_pp0_iter17_reg <= and_ln762_reg_575_pp0_iter16_reg;
        and_ln762_reg_575_pp0_iter18_reg <= and_ln762_reg_575_pp0_iter17_reg;
        and_ln762_reg_575_pp0_iter19_reg <= and_ln762_reg_575_pp0_iter18_reg;
        and_ln762_reg_575_pp0_iter1_reg <= and_ln762_reg_575;
        and_ln762_reg_575_pp0_iter20_reg <= and_ln762_reg_575_pp0_iter19_reg;
        and_ln762_reg_575_pp0_iter21_reg <= and_ln762_reg_575_pp0_iter20_reg;
        and_ln762_reg_575_pp0_iter22_reg <= and_ln762_reg_575_pp0_iter21_reg;
        and_ln762_reg_575_pp0_iter2_reg <= and_ln762_reg_575_pp0_iter1_reg;
        and_ln762_reg_575_pp0_iter3_reg <= and_ln762_reg_575_pp0_iter2_reg;
        and_ln762_reg_575_pp0_iter4_reg <= and_ln762_reg_575_pp0_iter3_reg;
        and_ln762_reg_575_pp0_iter5_reg <= and_ln762_reg_575_pp0_iter4_reg;
        and_ln762_reg_575_pp0_iter6_reg <= and_ln762_reg_575_pp0_iter5_reg;
        and_ln762_reg_575_pp0_iter7_reg <= and_ln762_reg_575_pp0_iter6_reg;
        and_ln762_reg_575_pp0_iter8_reg <= and_ln762_reg_575_pp0_iter7_reg;
        and_ln762_reg_575_pp0_iter9_reg <= and_ln762_reg_575_pp0_iter8_reg;
        ap_phi_reg_pp0_iter10_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter9_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter10_c_reg_88 <= ap_phi_reg_pp0_iter9_c_reg_88;
        ap_phi_reg_pp0_iter11_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter10_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter11_c_reg_88 <= ap_phi_reg_pp0_iter10_c_reg_88;
        ap_phi_reg_pp0_iter12_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter11_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter12_c_reg_88 <= ap_phi_reg_pp0_iter11_c_reg_88;
        ap_phi_reg_pp0_iter13_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter12_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter13_c_reg_88 <= ap_phi_reg_pp0_iter12_c_reg_88;
        ap_phi_reg_pp0_iter14_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter13_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter14_c_reg_88 <= ap_phi_reg_pp0_iter13_c_reg_88;
        ap_phi_reg_pp0_iter15_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter14_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter15_c_reg_88 <= ap_phi_reg_pp0_iter14_c_reg_88;
        ap_phi_reg_pp0_iter16_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter15_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter16_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter17_c_reg_88 <= ap_phi_reg_pp0_iter16_c_reg_88;
        ap_phi_reg_pp0_iter18_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter17_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter18_c_reg_88 <= ap_phi_reg_pp0_iter17_c_reg_88;
        ap_phi_reg_pp0_iter19_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter18_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter19_c_reg_88 <= ap_phi_reg_pp0_iter18_c_reg_88;
        ap_phi_reg_pp0_iter20_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter19_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter22_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter21_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter23_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter22_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter2_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter1_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter2_c_reg_88 <= ap_phi_reg_pp0_iter1_c_reg_88;
        ap_phi_reg_pp0_iter3_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter2_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter3_c_reg_88 <= ap_phi_reg_pp0_iter2_c_reg_88;
        ap_phi_reg_pp0_iter4_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter3_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter4_c_reg_88 <= ap_phi_reg_pp0_iter3_c_reg_88;
        ap_phi_reg_pp0_iter5_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter4_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter5_c_reg_88 <= ap_phi_reg_pp0_iter4_c_reg_88;
        ap_phi_reg_pp0_iter6_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter5_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter6_c_reg_88 <= ap_phi_reg_pp0_iter5_c_reg_88;
        ap_phi_reg_pp0_iter7_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter6_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter7_c_reg_88 <= ap_phi_reg_pp0_iter6_c_reg_88;
        ap_phi_reg_pp0_iter8_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter7_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter8_c_reg_88 <= ap_phi_reg_pp0_iter7_c_reg_88;
        ap_phi_reg_pp0_iter9_UnifiedRetVal_reg_102 <= ap_phi_reg_pp0_iter8_UnifiedRetVal_reg_102;
        ap_phi_reg_pp0_iter9_c_reg_88 <= ap_phi_reg_pp0_iter8_c_reg_88;
        b_reg_602_pp0_iter1_reg[30 : 0] <= b_reg_602[30 : 0];
        c_reg_88 <= ap_phi_reg_pp0_iter20_c_reg_88;
        c_reg_88_pp0_iter21_reg <= c_reg_88;
        c_reg_88_pp0_iter22_reg <= c_reg_88_pp0_iter21_reg;
        icmp_ln1018_4_reg_579_pp0_iter10_reg <= icmp_ln1018_4_reg_579_pp0_iter9_reg;
        icmp_ln1018_4_reg_579_pp0_iter11_reg <= icmp_ln1018_4_reg_579_pp0_iter10_reg;
        icmp_ln1018_4_reg_579_pp0_iter12_reg <= icmp_ln1018_4_reg_579_pp0_iter11_reg;
        icmp_ln1018_4_reg_579_pp0_iter13_reg <= icmp_ln1018_4_reg_579_pp0_iter12_reg;
        icmp_ln1018_4_reg_579_pp0_iter14_reg <= icmp_ln1018_4_reg_579_pp0_iter13_reg;
        icmp_ln1018_4_reg_579_pp0_iter15_reg <= icmp_ln1018_4_reg_579_pp0_iter14_reg;
        icmp_ln1018_4_reg_579_pp0_iter16_reg <= icmp_ln1018_4_reg_579_pp0_iter15_reg;
        icmp_ln1018_4_reg_579_pp0_iter17_reg <= icmp_ln1018_4_reg_579_pp0_iter16_reg;
        icmp_ln1018_4_reg_579_pp0_iter18_reg <= icmp_ln1018_4_reg_579_pp0_iter17_reg;
        icmp_ln1018_4_reg_579_pp0_iter19_reg <= icmp_ln1018_4_reg_579_pp0_iter18_reg;
        icmp_ln1018_4_reg_579_pp0_iter1_reg <= icmp_ln1018_4_reg_579;
        icmp_ln1018_4_reg_579_pp0_iter20_reg <= icmp_ln1018_4_reg_579_pp0_iter19_reg;
        icmp_ln1018_4_reg_579_pp0_iter21_reg <= icmp_ln1018_4_reg_579_pp0_iter20_reg;
        icmp_ln1018_4_reg_579_pp0_iter22_reg <= icmp_ln1018_4_reg_579_pp0_iter21_reg;
        icmp_ln1018_4_reg_579_pp0_iter23_reg <= icmp_ln1018_4_reg_579_pp0_iter22_reg;
        icmp_ln1018_4_reg_579_pp0_iter2_reg <= icmp_ln1018_4_reg_579_pp0_iter1_reg;
        icmp_ln1018_4_reg_579_pp0_iter3_reg <= icmp_ln1018_4_reg_579_pp0_iter2_reg;
        icmp_ln1018_4_reg_579_pp0_iter4_reg <= icmp_ln1018_4_reg_579_pp0_iter3_reg;
        icmp_ln1018_4_reg_579_pp0_iter5_reg <= icmp_ln1018_4_reg_579_pp0_iter4_reg;
        icmp_ln1018_4_reg_579_pp0_iter6_reg <= icmp_ln1018_4_reg_579_pp0_iter5_reg;
        icmp_ln1018_4_reg_579_pp0_iter7_reg <= icmp_ln1018_4_reg_579_pp0_iter6_reg;
        icmp_ln1018_4_reg_579_pp0_iter8_reg <= icmp_ln1018_4_reg_579_pp0_iter7_reg;
        icmp_ln1018_4_reg_579_pp0_iter9_reg <= icmp_ln1018_4_reg_579_pp0_iter8_reg;
        icmp_ln1018_5_reg_609_pp0_iter10_reg <= icmp_ln1018_5_reg_609_pp0_iter9_reg;
        icmp_ln1018_5_reg_609_pp0_iter11_reg <= icmp_ln1018_5_reg_609_pp0_iter10_reg;
        icmp_ln1018_5_reg_609_pp0_iter12_reg <= icmp_ln1018_5_reg_609_pp0_iter11_reg;
        icmp_ln1018_5_reg_609_pp0_iter13_reg <= icmp_ln1018_5_reg_609_pp0_iter12_reg;
        icmp_ln1018_5_reg_609_pp0_iter14_reg <= icmp_ln1018_5_reg_609_pp0_iter13_reg;
        icmp_ln1018_5_reg_609_pp0_iter15_reg <= icmp_ln1018_5_reg_609_pp0_iter14_reg;
        icmp_ln1018_5_reg_609_pp0_iter16_reg <= icmp_ln1018_5_reg_609_pp0_iter15_reg;
        icmp_ln1018_5_reg_609_pp0_iter17_reg <= icmp_ln1018_5_reg_609_pp0_iter16_reg;
        icmp_ln1018_5_reg_609_pp0_iter18_reg <= icmp_ln1018_5_reg_609_pp0_iter17_reg;
        icmp_ln1018_5_reg_609_pp0_iter1_reg <= icmp_ln1018_5_reg_609;
        icmp_ln1018_5_reg_609_pp0_iter2_reg <= icmp_ln1018_5_reg_609_pp0_iter1_reg;
        icmp_ln1018_5_reg_609_pp0_iter3_reg <= icmp_ln1018_5_reg_609_pp0_iter2_reg;
        icmp_ln1018_5_reg_609_pp0_iter4_reg <= icmp_ln1018_5_reg_609_pp0_iter3_reg;
        icmp_ln1018_5_reg_609_pp0_iter5_reg <= icmp_ln1018_5_reg_609_pp0_iter4_reg;
        icmp_ln1018_5_reg_609_pp0_iter6_reg <= icmp_ln1018_5_reg_609_pp0_iter5_reg;
        icmp_ln1018_5_reg_609_pp0_iter7_reg <= icmp_ln1018_5_reg_609_pp0_iter6_reg;
        icmp_ln1018_5_reg_609_pp0_iter8_reg <= icmp_ln1018_5_reg_609_pp0_iter7_reg;
        icmp_ln1018_5_reg_609_pp0_iter9_reg <= icmp_ln1018_5_reg_609_pp0_iter8_reg;
        icmp_ln1018_reg_571_pp0_iter10_reg <= icmp_ln1018_reg_571_pp0_iter9_reg;
        icmp_ln1018_reg_571_pp0_iter11_reg <= icmp_ln1018_reg_571_pp0_iter10_reg;
        icmp_ln1018_reg_571_pp0_iter12_reg <= icmp_ln1018_reg_571_pp0_iter11_reg;
        icmp_ln1018_reg_571_pp0_iter13_reg <= icmp_ln1018_reg_571_pp0_iter12_reg;
        icmp_ln1018_reg_571_pp0_iter14_reg <= icmp_ln1018_reg_571_pp0_iter13_reg;
        icmp_ln1018_reg_571_pp0_iter15_reg <= icmp_ln1018_reg_571_pp0_iter14_reg;
        icmp_ln1018_reg_571_pp0_iter16_reg <= icmp_ln1018_reg_571_pp0_iter15_reg;
        icmp_ln1018_reg_571_pp0_iter17_reg <= icmp_ln1018_reg_571_pp0_iter16_reg;
        icmp_ln1018_reg_571_pp0_iter18_reg <= icmp_ln1018_reg_571_pp0_iter17_reg;
        icmp_ln1018_reg_571_pp0_iter19_reg <= icmp_ln1018_reg_571_pp0_iter18_reg;
        icmp_ln1018_reg_571_pp0_iter1_reg <= icmp_ln1018_reg_571;
        icmp_ln1018_reg_571_pp0_iter20_reg <= icmp_ln1018_reg_571_pp0_iter19_reg;
        icmp_ln1018_reg_571_pp0_iter21_reg <= icmp_ln1018_reg_571_pp0_iter20_reg;
        icmp_ln1018_reg_571_pp0_iter22_reg <= icmp_ln1018_reg_571_pp0_iter21_reg;
        icmp_ln1018_reg_571_pp0_iter23_reg <= icmp_ln1018_reg_571_pp0_iter22_reg;
        icmp_ln1018_reg_571_pp0_iter2_reg <= icmp_ln1018_reg_571_pp0_iter1_reg;
        icmp_ln1018_reg_571_pp0_iter3_reg <= icmp_ln1018_reg_571_pp0_iter2_reg;
        icmp_ln1018_reg_571_pp0_iter4_reg <= icmp_ln1018_reg_571_pp0_iter3_reg;
        icmp_ln1018_reg_571_pp0_iter5_reg <= icmp_ln1018_reg_571_pp0_iter4_reg;
        icmp_ln1018_reg_571_pp0_iter6_reg <= icmp_ln1018_reg_571_pp0_iter5_reg;
        icmp_ln1018_reg_571_pp0_iter7_reg <= icmp_ln1018_reg_571_pp0_iter6_reg;
        icmp_ln1018_reg_571_pp0_iter8_reg <= icmp_ln1018_reg_571_pp0_iter7_reg;
        icmp_ln1018_reg_571_pp0_iter9_reg <= icmp_ln1018_reg_571_pp0_iter8_reg;
        icmp_ln1022_reg_553 <= icmp_ln1022_fu_257_p2;
        icmp_ln1022_reg_553_pp0_iter10_reg <= icmp_ln1022_reg_553_pp0_iter9_reg;
        icmp_ln1022_reg_553_pp0_iter11_reg <= icmp_ln1022_reg_553_pp0_iter10_reg;
        icmp_ln1022_reg_553_pp0_iter12_reg <= icmp_ln1022_reg_553_pp0_iter11_reg;
        icmp_ln1022_reg_553_pp0_iter13_reg <= icmp_ln1022_reg_553_pp0_iter12_reg;
        icmp_ln1022_reg_553_pp0_iter14_reg <= icmp_ln1022_reg_553_pp0_iter13_reg;
        icmp_ln1022_reg_553_pp0_iter15_reg <= icmp_ln1022_reg_553_pp0_iter14_reg;
        icmp_ln1022_reg_553_pp0_iter16_reg <= icmp_ln1022_reg_553_pp0_iter15_reg;
        icmp_ln1022_reg_553_pp0_iter17_reg <= icmp_ln1022_reg_553_pp0_iter16_reg;
        icmp_ln1022_reg_553_pp0_iter18_reg <= icmp_ln1022_reg_553_pp0_iter17_reg;
        icmp_ln1022_reg_553_pp0_iter19_reg <= icmp_ln1022_reg_553_pp0_iter18_reg;
        icmp_ln1022_reg_553_pp0_iter1_reg <= icmp_ln1022_reg_553;
        icmp_ln1022_reg_553_pp0_iter20_reg <= icmp_ln1022_reg_553_pp0_iter19_reg;
        icmp_ln1022_reg_553_pp0_iter21_reg <= icmp_ln1022_reg_553_pp0_iter20_reg;
        icmp_ln1022_reg_553_pp0_iter22_reg <= icmp_ln1022_reg_553_pp0_iter21_reg;
        icmp_ln1022_reg_553_pp0_iter2_reg <= icmp_ln1022_reg_553_pp0_iter1_reg;
        icmp_ln1022_reg_553_pp0_iter3_reg <= icmp_ln1022_reg_553_pp0_iter2_reg;
        icmp_ln1022_reg_553_pp0_iter4_reg <= icmp_ln1022_reg_553_pp0_iter3_reg;
        icmp_ln1022_reg_553_pp0_iter5_reg <= icmp_ln1022_reg_553_pp0_iter4_reg;
        icmp_ln1022_reg_553_pp0_iter6_reg <= icmp_ln1022_reg_553_pp0_iter5_reg;
        icmp_ln1022_reg_553_pp0_iter7_reg <= icmp_ln1022_reg_553_pp0_iter6_reg;
        icmp_ln1022_reg_553_pp0_iter8_reg <= icmp_ln1022_reg_553_pp0_iter7_reg;
        icmp_ln1022_reg_553_pp0_iter9_reg <= icmp_ln1022_reg_553_pp0_iter8_reg;
        icmp_ln766_reg_583_pp0_iter10_reg <= icmp_ln766_reg_583_pp0_iter9_reg;
        icmp_ln766_reg_583_pp0_iter11_reg <= icmp_ln766_reg_583_pp0_iter10_reg;
        icmp_ln766_reg_583_pp0_iter12_reg <= icmp_ln766_reg_583_pp0_iter11_reg;
        icmp_ln766_reg_583_pp0_iter13_reg <= icmp_ln766_reg_583_pp0_iter12_reg;
        icmp_ln766_reg_583_pp0_iter14_reg <= icmp_ln766_reg_583_pp0_iter13_reg;
        icmp_ln766_reg_583_pp0_iter15_reg <= icmp_ln766_reg_583_pp0_iter14_reg;
        icmp_ln766_reg_583_pp0_iter16_reg <= icmp_ln766_reg_583_pp0_iter15_reg;
        icmp_ln766_reg_583_pp0_iter17_reg <= icmp_ln766_reg_583_pp0_iter16_reg;
        icmp_ln766_reg_583_pp0_iter18_reg <= icmp_ln766_reg_583_pp0_iter17_reg;
        icmp_ln766_reg_583_pp0_iter19_reg <= icmp_ln766_reg_583_pp0_iter18_reg;
        icmp_ln766_reg_583_pp0_iter1_reg <= icmp_ln766_reg_583;
        icmp_ln766_reg_583_pp0_iter20_reg <= icmp_ln766_reg_583_pp0_iter19_reg;
        icmp_ln766_reg_583_pp0_iter21_reg <= icmp_ln766_reg_583_pp0_iter20_reg;
        icmp_ln766_reg_583_pp0_iter22_reg <= icmp_ln766_reg_583_pp0_iter21_reg;
        icmp_ln766_reg_583_pp0_iter23_reg <= icmp_ln766_reg_583_pp0_iter22_reg;
        icmp_ln766_reg_583_pp0_iter2_reg <= icmp_ln766_reg_583_pp0_iter1_reg;
        icmp_ln766_reg_583_pp0_iter3_reg <= icmp_ln766_reg_583_pp0_iter2_reg;
        icmp_ln766_reg_583_pp0_iter4_reg <= icmp_ln766_reg_583_pp0_iter3_reg;
        icmp_ln766_reg_583_pp0_iter5_reg <= icmp_ln766_reg_583_pp0_iter4_reg;
        icmp_ln766_reg_583_pp0_iter6_reg <= icmp_ln766_reg_583_pp0_iter5_reg;
        icmp_ln766_reg_583_pp0_iter7_reg <= icmp_ln766_reg_583_pp0_iter6_reg;
        icmp_ln766_reg_583_pp0_iter8_reg <= icmp_ln766_reg_583_pp0_iter7_reg;
        icmp_ln766_reg_583_pp0_iter9_reg <= icmp_ln766_reg_583_pp0_iter8_reg;
        or_ln757_1_reg_567_pp0_iter10_reg <= or_ln757_1_reg_567_pp0_iter9_reg;
        or_ln757_1_reg_567_pp0_iter11_reg <= or_ln757_1_reg_567_pp0_iter10_reg;
        or_ln757_1_reg_567_pp0_iter12_reg <= or_ln757_1_reg_567_pp0_iter11_reg;
        or_ln757_1_reg_567_pp0_iter13_reg <= or_ln757_1_reg_567_pp0_iter12_reg;
        or_ln757_1_reg_567_pp0_iter14_reg <= or_ln757_1_reg_567_pp0_iter13_reg;
        or_ln757_1_reg_567_pp0_iter15_reg <= or_ln757_1_reg_567_pp0_iter14_reg;
        or_ln757_1_reg_567_pp0_iter16_reg <= or_ln757_1_reg_567_pp0_iter15_reg;
        or_ln757_1_reg_567_pp0_iter17_reg <= or_ln757_1_reg_567_pp0_iter16_reg;
        or_ln757_1_reg_567_pp0_iter18_reg <= or_ln757_1_reg_567_pp0_iter17_reg;
        or_ln757_1_reg_567_pp0_iter19_reg <= or_ln757_1_reg_567_pp0_iter18_reg;
        or_ln757_1_reg_567_pp0_iter1_reg <= or_ln757_1_reg_567;
        or_ln757_1_reg_567_pp0_iter20_reg <= or_ln757_1_reg_567_pp0_iter19_reg;
        or_ln757_1_reg_567_pp0_iter21_reg <= or_ln757_1_reg_567_pp0_iter20_reg;
        or_ln757_1_reg_567_pp0_iter22_reg <= or_ln757_1_reg_567_pp0_iter21_reg;
        or_ln757_1_reg_567_pp0_iter23_reg <= or_ln757_1_reg_567_pp0_iter22_reg;
        or_ln757_1_reg_567_pp0_iter2_reg <= or_ln757_1_reg_567_pp0_iter1_reg;
        or_ln757_1_reg_567_pp0_iter3_reg <= or_ln757_1_reg_567_pp0_iter2_reg;
        or_ln757_1_reg_567_pp0_iter4_reg <= or_ln757_1_reg_567_pp0_iter3_reg;
        or_ln757_1_reg_567_pp0_iter5_reg <= or_ln757_1_reg_567_pp0_iter4_reg;
        or_ln757_1_reg_567_pp0_iter6_reg <= or_ln757_1_reg_567_pp0_iter5_reg;
        or_ln757_1_reg_567_pp0_iter7_reg <= or_ln757_1_reg_567_pp0_iter6_reg;
        or_ln757_1_reg_567_pp0_iter8_reg <= or_ln757_1_reg_567_pp0_iter7_reg;
        or_ln757_1_reg_567_pp0_iter9_reg <= or_ln757_1_reg_567_pp0_iter8_reg;
        or_ln757_reg_558 <= or_ln757_fu_263_p2;
        or_ln757_reg_558_pp0_iter10_reg <= or_ln757_reg_558_pp0_iter9_reg;
        or_ln757_reg_558_pp0_iter11_reg <= or_ln757_reg_558_pp0_iter10_reg;
        or_ln757_reg_558_pp0_iter12_reg <= or_ln757_reg_558_pp0_iter11_reg;
        or_ln757_reg_558_pp0_iter13_reg <= or_ln757_reg_558_pp0_iter12_reg;
        or_ln757_reg_558_pp0_iter14_reg <= or_ln757_reg_558_pp0_iter13_reg;
        or_ln757_reg_558_pp0_iter15_reg <= or_ln757_reg_558_pp0_iter14_reg;
        or_ln757_reg_558_pp0_iter16_reg <= or_ln757_reg_558_pp0_iter15_reg;
        or_ln757_reg_558_pp0_iter17_reg <= or_ln757_reg_558_pp0_iter16_reg;
        or_ln757_reg_558_pp0_iter18_reg <= or_ln757_reg_558_pp0_iter17_reg;
        or_ln757_reg_558_pp0_iter19_reg <= or_ln757_reg_558_pp0_iter18_reg;
        or_ln757_reg_558_pp0_iter1_reg <= or_ln757_reg_558;
        or_ln757_reg_558_pp0_iter20_reg <= or_ln757_reg_558_pp0_iter19_reg;
        or_ln757_reg_558_pp0_iter21_reg <= or_ln757_reg_558_pp0_iter20_reg;
        or_ln757_reg_558_pp0_iter22_reg <= or_ln757_reg_558_pp0_iter21_reg;
        or_ln757_reg_558_pp0_iter23_reg <= or_ln757_reg_558_pp0_iter22_reg;
        or_ln757_reg_558_pp0_iter2_reg <= or_ln757_reg_558_pp0_iter1_reg;
        or_ln757_reg_558_pp0_iter3_reg <= or_ln757_reg_558_pp0_iter2_reg;
        or_ln757_reg_558_pp0_iter4_reg <= or_ln757_reg_558_pp0_iter3_reg;
        or_ln757_reg_558_pp0_iter5_reg <= or_ln757_reg_558_pp0_iter4_reg;
        or_ln757_reg_558_pp0_iter6_reg <= or_ln757_reg_558_pp0_iter5_reg;
        or_ln757_reg_558_pp0_iter7_reg <= or_ln757_reg_558_pp0_iter6_reg;
        or_ln757_reg_558_pp0_iter8_reg <= or_ln757_reg_558_pp0_iter7_reg;
        or_ln757_reg_558_pp0_iter9_reg <= or_ln757_reg_558_pp0_iter8_reg;
        p_Result_14_reg_541 <= data_V_4_fu_219_p1[32'd31];
        p_Result_14_reg_541_pp0_iter10_reg <= p_Result_14_reg_541_pp0_iter9_reg;
        p_Result_14_reg_541_pp0_iter11_reg <= p_Result_14_reg_541_pp0_iter10_reg;
        p_Result_14_reg_541_pp0_iter12_reg <= p_Result_14_reg_541_pp0_iter11_reg;
        p_Result_14_reg_541_pp0_iter13_reg <= p_Result_14_reg_541_pp0_iter12_reg;
        p_Result_14_reg_541_pp0_iter14_reg <= p_Result_14_reg_541_pp0_iter13_reg;
        p_Result_14_reg_541_pp0_iter15_reg <= p_Result_14_reg_541_pp0_iter14_reg;
        p_Result_14_reg_541_pp0_iter16_reg <= p_Result_14_reg_541_pp0_iter15_reg;
        p_Result_14_reg_541_pp0_iter17_reg <= p_Result_14_reg_541_pp0_iter16_reg;
        p_Result_14_reg_541_pp0_iter18_reg <= p_Result_14_reg_541_pp0_iter17_reg;
        p_Result_14_reg_541_pp0_iter19_reg <= p_Result_14_reg_541_pp0_iter18_reg;
        p_Result_14_reg_541_pp0_iter1_reg <= p_Result_14_reg_541;
        p_Result_14_reg_541_pp0_iter20_reg <= p_Result_14_reg_541_pp0_iter19_reg;
        p_Result_14_reg_541_pp0_iter21_reg <= p_Result_14_reg_541_pp0_iter20_reg;
        p_Result_14_reg_541_pp0_iter22_reg <= p_Result_14_reg_541_pp0_iter21_reg;
        p_Result_14_reg_541_pp0_iter2_reg <= p_Result_14_reg_541_pp0_iter1_reg;
        p_Result_14_reg_541_pp0_iter3_reg <= p_Result_14_reg_541_pp0_iter2_reg;
        p_Result_14_reg_541_pp0_iter4_reg <= p_Result_14_reg_541_pp0_iter3_reg;
        p_Result_14_reg_541_pp0_iter5_reg <= p_Result_14_reg_541_pp0_iter4_reg;
        p_Result_14_reg_541_pp0_iter6_reg <= p_Result_14_reg_541_pp0_iter5_reg;
        p_Result_14_reg_541_pp0_iter7_reg <= p_Result_14_reg_541_pp0_iter6_reg;
        p_Result_14_reg_541_pp0_iter8_reg <= p_Result_14_reg_541_pp0_iter7_reg;
        p_Result_14_reg_541_pp0_iter9_reg <= p_Result_14_reg_541_pp0_iter8_reg;
        p_Result_s_reg_536 <= data_V_fu_193_p1[32'd31];
        p_Result_s_reg_536_pp0_iter10_reg <= p_Result_s_reg_536_pp0_iter9_reg;
        p_Result_s_reg_536_pp0_iter11_reg <= p_Result_s_reg_536_pp0_iter10_reg;
        p_Result_s_reg_536_pp0_iter12_reg <= p_Result_s_reg_536_pp0_iter11_reg;
        p_Result_s_reg_536_pp0_iter13_reg <= p_Result_s_reg_536_pp0_iter12_reg;
        p_Result_s_reg_536_pp0_iter14_reg <= p_Result_s_reg_536_pp0_iter13_reg;
        p_Result_s_reg_536_pp0_iter15_reg <= p_Result_s_reg_536_pp0_iter14_reg;
        p_Result_s_reg_536_pp0_iter16_reg <= p_Result_s_reg_536_pp0_iter15_reg;
        p_Result_s_reg_536_pp0_iter17_reg <= p_Result_s_reg_536_pp0_iter16_reg;
        p_Result_s_reg_536_pp0_iter18_reg <= p_Result_s_reg_536_pp0_iter17_reg;
        p_Result_s_reg_536_pp0_iter19_reg <= p_Result_s_reg_536_pp0_iter18_reg;
        p_Result_s_reg_536_pp0_iter1_reg <= p_Result_s_reg_536;
        p_Result_s_reg_536_pp0_iter20_reg <= p_Result_s_reg_536_pp0_iter19_reg;
        p_Result_s_reg_536_pp0_iter21_reg <= p_Result_s_reg_536_pp0_iter20_reg;
        p_Result_s_reg_536_pp0_iter22_reg <= p_Result_s_reg_536_pp0_iter21_reg;
        p_Result_s_reg_536_pp0_iter2_reg <= p_Result_s_reg_536_pp0_iter1_reg;
        p_Result_s_reg_536_pp0_iter3_reg <= p_Result_s_reg_536_pp0_iter2_reg;
        p_Result_s_reg_536_pp0_iter4_reg <= p_Result_s_reg_536_pp0_iter3_reg;
        p_Result_s_reg_536_pp0_iter5_reg <= p_Result_s_reg_536_pp0_iter4_reg;
        p_Result_s_reg_536_pp0_iter6_reg <= p_Result_s_reg_536_pp0_iter5_reg;
        p_Result_s_reg_536_pp0_iter7_reg <= p_Result_s_reg_536_pp0_iter6_reg;
        p_Result_s_reg_536_pp0_iter8_reg <= p_Result_s_reg_536_pp0_iter7_reg;
        p_Result_s_reg_536_pp0_iter9_reg <= p_Result_s_reg_536_pp0_iter8_reg;
        tmp_3_reg_632_pp0_iter21_reg <= tmp_3_reg_632;
        tmp_3_reg_632_pp0_iter22_reg <= tmp_3_reg_632_pp0_iter21_reg;
        tmp_3_reg_632_pp0_iter23_reg <= tmp_3_reg_632_pp0_iter22_reg;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln766_fu_339_p2 == 1'd0) & (icmp_ln1018_4_fu_305_p2 == 1'd0) & (icmp_ln1018_fu_293_p2 == 1'd0) & (or_ln757_1_fu_287_p2 == 1'd1) & (1'b1 == ap_ce_reg) & (or_ln757_fu_263_p2 == 1'd1))) begin
        and_ln18_2_reg_591 <= and_ln18_2_fu_351_p2;
        and_ln18_reg_587 <= and_ln18_fu_345_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln1018_5_reg_609 == 1'd0) & (icmp_ln1018_4_reg_579 == 1'd0) & (icmp_ln766_reg_583 == 1'd0) & (1'd0 == and_ln18_2_reg_591) & (1'd0 == and_ln18_reg_587) & (icmp_ln1018_reg_571 == 1'd0) & (or_ln757_1_reg_567 == 1'd1) & (or_ln757_reg_558 == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        and_ln746_1_reg_623 <= and_ln746_1_fu_423_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1018_fu_293_p2 == 1'd1) & (or_ln757_1_fu_287_p2 == 1'd1) & (1'b1 == ap_ce_reg) & (or_ln757_fu_263_p2 == 1'd1))) begin
        and_ln762_reg_575 <= and_ln762_fu_299_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce_reg)) begin
        ap_return_int_reg <= ap_phi_mux_UnifiedRetVal_phi_fu_114_p40;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln18_2_reg_591_pp0_iter22_reg) & (1'd0 == and_ln18_reg_587_pp0_iter22_reg) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln766_reg_583_pp0_iter22_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter22_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter22_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter22_reg == 1'd1) & (1'b1 == ap_ce_reg) & (or_ln757_reg_558_pp0_iter22_reg == 1'd1))) begin
        d_reg_636 <= grp_fu_177_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg) & (((icmp_ln1018_fu_293_p2 == 1'd0) & (or_ln757_1_fu_287_p2 == 1'd1) & (or_ln757_fu_263_p2 == 1'd1)) | ((1'd0 == and_ln762_fu_299_p2) & (or_ln757_1_fu_287_p2 == 1'd1) & (or_ln757_fu_263_p2 == 1'd1) & (icmp_ln1022_fu_257_p2 == 1'd0))))) begin
        icmp_ln1018_4_reg_579 <= icmp_ln1018_4_fu_305_p2;
        icmp_ln766_reg_583 <= icmp_ln766_fu_339_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (or_ln757_1_fu_287_p2 == 1'd1) & (1'b1 == ap_ce_reg) & (or_ln757_fu_263_p2 == 1'd1))) begin
        icmp_ln1018_reg_571 <= icmp_ln1018_fu_293_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg) & (or_ln757_fu_263_p2 == 1'd1))) begin
        icmp_ln1022_1_reg_562 <= icmp_ln1022_1_fu_281_p2;
        or_ln757_1_reg_567 <= or_ln757_1_fu_287_p2;
    end
end

always @ (posedge ap_clk) begin
    if (((1'd0 == and_ln18_2_fu_351_p2) & (1'd0 == and_ln18_fu_345_p2) & (1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln1018_5_fu_391_p2 == 1'd0) & (icmp_ln766_fu_339_p2 == 1'd0) & (icmp_ln1018_4_fu_305_p2 == 1'd0) & (icmp_ln1018_fu_293_p2 == 1'd0) & (or_ln757_1_fu_287_p2 == 1'd1) & (1'b1 == ap_ce_reg) & (or_ln757_fu_263_p2 == 1'd1))) begin
        icmp_ln746_1_reg_618 <= icmp_ln746_1_fu_403_p2;
        icmp_ln746_reg_613 <= icmp_ln746_fu_397_p2;
    end
end

always @ (posedge ap_clk) begin
    if ((((icmp_ln1018_5_reg_609_pp0_iter14_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter14_reg == 1'd0) & (icmp_ln766_reg_583_pp0_iter14_reg == 1'd0) & (1'd0 == and_ln746_1_reg_623_pp0_iter14_reg) & (1'd0 == and_ln18_2_reg_591_pp0_iter14_reg) & (1'd0 == and_ln18_reg_587_pp0_iter14_reg) & (icmp_ln1018_reg_571_pp0_iter14_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter14_reg == 1'd1) & (or_ln757_reg_558_pp0_iter14_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg)) | ((icmp_ln1018_5_reg_609_pp0_iter14_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter14_reg == 1'd0) & (icmp_ln766_reg_583_pp0_iter14_reg == 1'd0) & (1'd0 == and_ln18_2_reg_591_pp0_iter14_reg) & (1'd0 == and_ln18_reg_587_pp0_iter14_reg) & (icmp_ln1018_reg_571_pp0_iter14_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter14_reg == 1'd1) & (1'd1 == and_ln746_1_reg_623_pp0_iter14_reg) & (or_ln757_reg_558_pp0_iter14_reg == 1'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg)))) begin
        reg_187 <= grp_atan2_generic_float_s_fu_166_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (icmp_ln766_reg_583_pp0_iter19_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter19_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter19_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter19_reg == 1'd1) & (1'b1 == ap_ce_reg) & (or_ln757_reg_558_pp0_iter19_reg == 1'd1))) begin
        tmp_3_reg_632 <= tmp_3_fu_429_p3;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_ce)) begin
        x_in_int_reg <= x_in;
        y_in_int_reg <= y_in;
    end
end

always @ (*) begin
    if (((1'd0 == and_ln18_2_reg_591_pp0_iter23_reg) & (1'd0 == and_ln18_reg_587_pp0_iter23_reg) & (tmp_3_reg_632_pp0_iter23_reg == 2'd3) & (icmp_ln766_reg_583_pp0_iter23_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter23_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter23_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter23_reg == 1'd1) & (or_ln757_reg_558_pp0_iter23_reg == 1'd1))) begin
        ap_phi_mux_UnifiedRetVal_phi_fu_114_p40 = bitcast_ln826_1_fu_531_p1;
    end else begin
        ap_phi_mux_UnifiedRetVal_phi_fu_114_p40 = ap_phi_reg_pp0_iter24_UnifiedRetVal_reg_102;
    end
end

always @ (*) begin
    if ((1'b0 == ap_ce_reg)) begin
        ap_return = ap_return_int_reg;
    end else if ((1'b1 == ap_ce_reg)) begin
        ap_return = ap_phi_mux_UnifiedRetVal_phi_fu_114_p40;
    end else begin
        ap_return = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001_ignoreCallOp84) & (1'b1 == ap_ce_reg))) begin
        grp_atan2_generic_float_s_fu_166_ap_ce = 1'b1;
    end else begin
        grp_atan2_generic_float_s_fu_166_ap_ce = 1'b0;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if ((ap_predicate_op85_call_state3 == 1'b1)) begin
            grp_atan2_generic_float_s_fu_166_x_in = a_reg_595_pp0_iter1_reg;
        end else if ((ap_predicate_op84_call_state3 == 1'b1)) begin
            grp_atan2_generic_float_s_fu_166_x_in = b_reg_602_pp0_iter1_reg;
        end else begin
            grp_atan2_generic_float_s_fu_166_x_in = 'bx;
        end
    end else begin
        grp_atan2_generic_float_s_fu_166_x_in = 'bx;
    end
end

always @ (*) begin
    if ((1'b0 == ap_block_pp0_stage0)) begin
        if ((ap_predicate_op85_call_state3 == 1'b1)) begin
            grp_atan2_generic_float_s_fu_166_y_in = b_reg_602_pp0_iter1_reg;
        end else if ((ap_predicate_op84_call_state3 == 1'b1)) begin
            grp_atan2_generic_float_s_fu_166_y_in = a_reg_595_pp0_iter1_reg;
        end else begin
            grp_atan2_generic_float_s_fu_166_y_in = 'bx;
        end
    end else begin
        grp_atan2_generic_float_s_fu_166_y_in = 'bx;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_172_ce = 1'b1;
    end else begin
        grp_fu_172_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_177_ce = 1'b1;
    end else begin
        grp_fu_177_ce = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_ce_reg))) begin
        grp_fu_183_ce = 1'b1;
    end else begin
        grp_fu_183_ce = 1'b0;
    end
end

assign a_fu_369_p1 = p_Result_21_fu_361_p3;

assign and_ln18_2_fu_351_p2 = (icmp_ln757_fu_245_p2 & icmp_ln1022_fu_257_p2);

assign and_ln18_fu_345_p2 = (icmp_ln757_1_fu_269_p2 & icmp_ln1022_1_fu_281_p2);

assign and_ln746_1_fu_423_p2 = (grp_fu_183_p2 & and_ln746_fu_417_p2);

assign and_ln746_fu_417_p2 = (or_ln746_fu_409_p2 & or_ln746_1_fu_413_p2);

assign and_ln762_fu_299_p2 = (p_Result_s_fu_197_p3 & icmp_ln1022_fu_257_p2);

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_00001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001_ignoreCallOp84 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9 = ~(1'b1 == 1'b1);

assign ap_block_state10_pp0_stage0_iter9_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10 = ~(1'b1 == 1'b1);

assign ap_block_state11_pp0_stage0_iter10_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11 = ~(1'b1 == 1'b1);

assign ap_block_state12_pp0_stage0_iter11_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12 = ~(1'b1 == 1'b1);

assign ap_block_state13_pp0_stage0_iter12_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13 = ~(1'b1 == 1'b1);

assign ap_block_state14_pp0_stage0_iter13_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14 = ~(1'b1 == 1'b1);

assign ap_block_state15_pp0_stage0_iter14_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15 = ~(1'b1 == 1'b1);

assign ap_block_state16_pp0_stage0_iter15_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16 = ~(1'b1 == 1'b1);

assign ap_block_state17_pp0_stage0_iter16_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17 = ~(1'b1 == 1'b1);

assign ap_block_state18_pp0_stage0_iter17_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18 = ~(1'b1 == 1'b1);

assign ap_block_state19_pp0_stage0_iter18_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19 = ~(1'b1 == 1'b1);

assign ap_block_state20_pp0_stage0_iter19_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20 = ~(1'b1 == 1'b1);

assign ap_block_state21_pp0_stage0_iter20_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21 = ~(1'b1 == 1'b1);

assign ap_block_state22_pp0_stage0_iter21_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22 = ~(1'b1 == 1'b1);

assign ap_block_state23_pp0_stage0_iter22_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23 = ~(1'b1 == 1'b1);

assign ap_block_state24_pp0_stage0_iter23_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter24 = ~(1'b1 == 1'b1);

assign ap_block_state25_pp0_stage0_iter24_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2 = ~(1'b1 == 1'b1);

assign ap_block_state3_pp0_stage0_iter2_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3 = ~(1'b1 == 1'b1);

assign ap_block_state4_pp0_stage0_iter3_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4 = ~(1'b1 == 1'b1);

assign ap_block_state5_pp0_stage0_iter4_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5 = ~(1'b1 == 1'b1);

assign ap_block_state6_pp0_stage0_iter5_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6 = ~(1'b1 == 1'b1);

assign ap_block_state7_pp0_stage0_iter6_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7 = ~(1'b1 == 1'b1);

assign ap_block_state8_pp0_stage0_iter7_ignore_call0 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8 = ~(1'b1 == 1'b1);

assign ap_block_state9_pp0_stage0_iter8_ignore_call0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_condition_1016 = ((1'd1 == and_ln18_2_reg_591_pp0_iter19_reg) & (1'd1 == and_ln18_reg_587_pp0_iter19_reg) & (tmp_3_fu_429_p3 == 2'd3) & (icmp_ln766_reg_583_pp0_iter19_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter19_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter19_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter19_reg == 1'd1) & (or_ln757_reg_558_pp0_iter19_reg == 1'd1));
end

always @ (*) begin
    ap_condition_1021 = ((1'd1 == and_ln18_2_reg_591_pp0_iter19_reg) & (1'd1 == and_ln18_reg_587_pp0_iter19_reg) & (tmp_3_fu_429_p3 == 2'd2) & (icmp_ln766_reg_583_pp0_iter19_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter19_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter19_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter19_reg == 1'd1) & (or_ln757_reg_558_pp0_iter19_reg == 1'd1));
end

always @ (*) begin
    ap_condition_1025 = ((1'd1 == and_ln18_2_reg_591_pp0_iter19_reg) & (1'd1 == and_ln18_reg_587_pp0_iter19_reg) & (tmp_3_fu_429_p3 == 2'd1) & (icmp_ln766_reg_583_pp0_iter19_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter19_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter19_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter19_reg == 1'd1) & (or_ln757_reg_558_pp0_iter19_reg == 1'd1));
end

always @ (*) begin
    ap_condition_1030 = ((1'd0 == and_ln18_2_reg_591_pp0_iter19_reg) & (1'd1 == and_ln18_reg_587_pp0_iter19_reg) & (tmp_3_fu_429_p3 == 2'd3) & (icmp_ln766_reg_583_pp0_iter19_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter19_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter19_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter19_reg == 1'd1) & (or_ln757_reg_558_pp0_iter19_reg == 1'd1));
end

always @ (*) begin
    ap_condition_1033 = ((1'd0 == and_ln18_2_reg_591_pp0_iter19_reg) & (1'd1 == and_ln18_reg_587_pp0_iter19_reg) & (tmp_3_fu_429_p3 == 2'd2) & (icmp_ln766_reg_583_pp0_iter19_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter19_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter19_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter19_reg == 1'd1) & (or_ln757_reg_558_pp0_iter19_reg == 1'd1));
end

always @ (*) begin
    ap_condition_1036 = ((1'd0 == and_ln18_2_reg_591_pp0_iter19_reg) & (1'd1 == and_ln18_reg_587_pp0_iter19_reg) & (tmp_3_fu_429_p3 == 2'd1) & (icmp_ln766_reg_583_pp0_iter19_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter19_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter19_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter19_reg == 1'd1) & (or_ln757_reg_558_pp0_iter19_reg == 1'd1));
end

always @ (*) begin
    ap_condition_1056 = ((1'd0 == and_ln18_2_reg_591_pp0_iter22_reg) & (1'd0 == and_ln18_reg_587_pp0_iter22_reg) & (tmp_3_reg_632_pp0_iter22_reg == 2'd2) & (icmp_ln766_reg_583_pp0_iter22_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter22_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter22_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter22_reg == 1'd1) & (or_ln757_reg_558_pp0_iter22_reg == 1'd1));
end

always @ (*) begin
    ap_condition_1063 = ((1'd0 == and_ln18_2_reg_591_pp0_iter19_reg) & (1'd0 == and_ln18_reg_587_pp0_iter19_reg) & (tmp_3_fu_429_p3 == 2'd0) & (icmp_ln766_reg_583_pp0_iter19_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter19_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter19_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter19_reg == 1'd1) & (or_ln757_reg_558_pp0_iter19_reg == 1'd1));
end

always @ (*) begin
    ap_condition_1065 = ((1'd1 == and_ln18_2_reg_591_pp0_iter19_reg) & (1'd1 == and_ln18_reg_587_pp0_iter19_reg) & (tmp_3_fu_429_p3 == 2'd0) & (icmp_ln766_reg_583_pp0_iter19_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter19_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter19_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter19_reg == 1'd1) & (or_ln757_reg_558_pp0_iter19_reg == 1'd1));
end

always @ (*) begin
    ap_condition_1068 = ((1'd0 == and_ln18_2_reg_591_pp0_iter19_reg) & (1'd1 == and_ln18_reg_587_pp0_iter19_reg) & (tmp_3_fu_429_p3 == 2'd0) & (icmp_ln766_reg_583_pp0_iter19_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter19_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter19_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter19_reg == 1'd1) & (or_ln757_reg_558_pp0_iter19_reg == 1'd1));
end

always @ (*) begin
    ap_condition_507 = ((1'd0 == and_ln18_2_reg_591_pp0_iter18_reg) & (1'd0 == and_ln18_reg_587_pp0_iter18_reg) & (1'd1 == and_ln746_1_reg_623_pp0_iter18_reg) & (icmp_ln1018_5_reg_609_pp0_iter18_reg == 1'd0) & (icmp_ln766_reg_583_pp0_iter18_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter18_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter18_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter18_reg == 1'd1) & (or_ln757_reg_558_pp0_iter18_reg == 1'd1));
end

always @ (*) begin
    ap_condition_545 = ((1'd0 == and_ln18_2_reg_591_pp0_iter22_reg) & (1'd0 == and_ln18_reg_587_pp0_iter22_reg) & (tmp_3_reg_632_pp0_iter22_reg == 2'd1) & (icmp_ln766_reg_583_pp0_iter22_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter22_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter22_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter22_reg == 1'd1) & (or_ln757_reg_558_pp0_iter22_reg == 1'd1));
end

always @ (*) begin
    ap_condition_550 = ((1'd0 == and_ln18_reg_587_pp0_iter22_reg) & (1'd1 == and_ln18_2_reg_591_pp0_iter22_reg) & (icmp_ln766_reg_583_pp0_iter22_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter22_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter22_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter22_reg == 1'd1) & (or_ln757_reg_558_pp0_iter22_reg == 1'd1));
end

always @ (*) begin
    ap_condition_555 = ((icmp_ln766_reg_583_pp0_iter22_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter22_reg == 1'd1) & (icmp_ln1018_reg_571_pp0_iter22_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter22_reg == 1'd1) & (or_ln757_reg_558_pp0_iter22_reg == 1'd1));
end

always @ (*) begin
    ap_condition_567 = ((1'd0 == and_ln762_reg_575_pp0_iter22_reg) & (icmp_ln766_reg_583_pp0_iter22_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter22_reg == 1'd1) & (or_ln757_1_reg_567_pp0_iter22_reg == 1'd1) & (or_ln757_reg_558_pp0_iter22_reg == 1'd1) & (icmp_ln1022_reg_553_pp0_iter22_reg == 1'd0) & (p_Result_s_reg_536_pp0_iter22_reg == 1'd0));
end

always @ (*) begin
    ap_condition_572 = ((1'd0 == and_ln762_reg_575_pp0_iter22_reg) & (icmp_ln766_reg_583_pp0_iter22_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter22_reg == 1'd1) & (or_ln757_1_reg_567_pp0_iter22_reg == 1'd1) & (or_ln757_reg_558_pp0_iter22_reg == 1'd1) & (icmp_ln1022_reg_553_pp0_iter22_reg == 1'd0) & (p_Result_s_reg_536_pp0_iter22_reg == 1'd1));
end

always @ (*) begin
    ap_condition_581 = (((icmp_ln766_reg_583_pp0_iter22_reg == 1'd1) & (icmp_ln1018_reg_571_pp0_iter22_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter22_reg == 1'd1) & (or_ln757_reg_558_pp0_iter22_reg == 1'd1)) | ((1'd0 == and_ln762_reg_575_pp0_iter22_reg) & (icmp_ln766_reg_583_pp0_iter22_reg == 1'd1) & (or_ln757_1_reg_567_pp0_iter22_reg == 1'd1) & (or_ln757_reg_558_pp0_iter22_reg == 1'd1) & (icmp_ln1022_reg_553_pp0_iter22_reg == 1'd0)));
end

always @ (*) begin
    ap_condition_586 = ((1'd0 == and_ln762_reg_575_pp0_iter22_reg) & (icmp_ln1018_reg_571_pp0_iter22_reg == 1'd1) & (or_ln757_1_reg_567_pp0_iter22_reg == 1'd1) & (or_ln757_reg_558_pp0_iter22_reg == 1'd1) & (icmp_ln1022_reg_553_pp0_iter22_reg == 1'd1));
end

always @ (*) begin
    ap_condition_591 = ((1'd1 == and_ln762_reg_575_pp0_iter22_reg) & (icmp_ln1018_reg_571_pp0_iter22_reg == 1'd1) & (or_ln757_1_reg_567_pp0_iter22_reg == 1'd1) & (or_ln757_reg_558_pp0_iter22_reg == 1'd1));
end

always @ (*) begin
    ap_condition_89 = ((icmp_ln1018_5_reg_609_pp0_iter14_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter14_reg == 1'd0) & (icmp_ln766_reg_583_pp0_iter14_reg == 1'd0) & (1'd0 == and_ln746_1_reg_623_pp0_iter14_reg) & (1'd0 == and_ln18_2_reg_591_pp0_iter14_reg) & (1'd0 == and_ln18_reg_587_pp0_iter14_reg) & (icmp_ln1018_reg_571_pp0_iter14_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter14_reg == 1'd1) & (or_ln757_reg_558_pp0_iter14_reg == 1'd1));
end

always @ (*) begin
    ap_condition_981 = ((1'd0 == and_ln18_2_fu_351_p2) & (1'd0 == and_ln18_fu_345_p2) & (icmp_ln1018_5_fu_391_p2 == 1'd1) & (icmp_ln766_fu_339_p2 == 1'd0) & (icmp_ln1018_4_fu_305_p2 == 1'd0) & (icmp_ln1018_fu_293_p2 == 1'd0) & (or_ln757_1_fu_287_p2 == 1'd1) & (or_ln757_fu_263_p2 == 1'd1));
end

assign ap_phi_reg_pp0_iter0_UnifiedRetVal_reg_102 = 'bx;

assign ap_phi_reg_pp0_iter0_c_reg_88 = 'bx;

always @ (*) begin
    ap_predicate_op75_fcmp_state1 = ((1'd0 == and_ln18_2_fu_351_p2) & (1'd0 == and_ln18_fu_345_p2) & (icmp_ln1018_5_fu_391_p2 == 1'd0) & (icmp_ln766_fu_339_p2 == 1'd0) & (icmp_ln1018_4_fu_305_p2 == 1'd0) & (icmp_ln1018_fu_293_p2 == 1'd0) & (or_ln757_1_fu_287_p2 == 1'd1) & (or_ln757_fu_263_p2 == 1'd1));
end

always @ (*) begin
    ap_predicate_op84_call_state3 = ((1'd0 == and_ln746_1_reg_623) & (1'd0 == and_ln18_2_reg_591_pp0_iter1_reg) & (1'd0 == and_ln18_reg_587_pp0_iter1_reg) & (icmp_ln1018_5_reg_609_pp0_iter1_reg == 1'd0) & (icmp_ln766_reg_583_pp0_iter1_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter1_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter1_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter1_reg == 1'd1) & (or_ln757_reg_558_pp0_iter1_reg == 1'd1));
end

always @ (*) begin
    ap_predicate_op85_call_state3 = ((1'd0 == and_ln18_2_reg_591_pp0_iter1_reg) & (1'd0 == and_ln18_reg_587_pp0_iter1_reg) & (1'd1 == and_ln746_1_reg_623) & (icmp_ln1018_5_reg_609_pp0_iter1_reg == 1'd0) & (icmp_ln766_reg_583_pp0_iter1_reg == 1'd0) & (icmp_ln1018_4_reg_579_pp0_iter1_reg == 1'd0) & (icmp_ln1018_reg_571_pp0_iter1_reg == 1'd0) & (or_ln757_1_reg_567_pp0_iter1_reg == 1'd1) & (or_ln757_reg_558_pp0_iter1_reg == 1'd1));
end

assign b_fu_386_p1 = p_Result_22_fu_378_p3;

assign bitcast_ln354_1_fu_507_p1 = p_Result_16_fu_500_p3;

assign bitcast_ln354_2_fu_496_p1 = p_Result_17_fu_489_p3;

assign bitcast_ln354_3_fu_485_p1 = p_Result_18_fu_478_p3;

assign bitcast_ln354_4_fu_474_p1 = p_Result_19_fu_467_p3;

assign bitcast_ln354_5_fu_463_p1 = p_Result_20_fu_456_p3;

assign bitcast_ln354_fu_518_p1 = p_Result_15_fu_511_p3;

assign bitcast_ln822_1_fu_445_p1 = xor_ln822_fu_439_p2;

assign bitcast_ln822_fu_435_p1 = c_reg_88_pp0_iter22_reg;

assign bitcast_ln826_1_fu_531_p1 = xor_ln826_fu_525_p2;

assign bitcast_ln826_fu_522_p1 = d_reg_636;

assign data_V_4_fu_219_p1 = y_in_int_reg;

assign data_V_fu_193_p1 = x_in_int_reg;

assign grp_fu_183_p0 = p_Result_21_fu_361_p3;

assign grp_fu_183_p1 = p_Result_22_fu_378_p3;

assign icmp_ln1018_4_fu_305_p2 = ((tmp_fu_205_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln1018_5_fu_391_p2 = ((p_Result_22_fu_378_p3 == p_Result_21_fu_361_p3) ? 1'b1 : 1'b0);

assign icmp_ln1018_fu_293_p2 = ((tmp_459_fu_231_p4 == 8'd0) ? 1'b1 : 1'b0);

assign icmp_ln1022_1_fu_281_p2 = ((tmp_458_fu_215_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln1022_fu_257_p2 = ((tmp_460_fu_241_p1 == 23'd0) ? 1'b1 : 1'b0);

assign icmp_ln746_1_fu_403_p2 = ((tmp_fu_205_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln746_fu_397_p2 = ((tmp_459_fu_231_p4 != 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln757_1_fu_269_p2 = ((tmp_fu_205_p4 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln757_fu_245_p2 = ((tmp_459_fu_231_p4 == 8'd255) ? 1'b1 : 1'b0);

assign icmp_ln766_fu_339_p2 = ((tmp_2_fu_331_p3 == 23'd0) ? 1'b1 : 1'b0);

assign or_ln746_1_fu_413_p2 = (icmp_ln746_1_reg_618 | icmp_ln1022_1_reg_562);

assign or_ln746_fu_409_p2 = (icmp_ln746_reg_613 | icmp_ln1022_reg_553);

assign or_ln757_1_fu_287_p2 = (xor_ln18_1_fu_275_p2 | icmp_ln1022_1_fu_281_p2);

assign or_ln757_fu_263_p2 = (xor_ln18_fu_251_p2 | icmp_ln1022_fu_257_p2);

assign or_ln766_fu_315_p2 = (trunc_ln766_fu_311_p1 | tmp_fu_205_p4);

assign p_Result_15_fu_511_p3 = {{p_Result_14_reg_541_pp0_iter22_reg}, {31'd1078530011}};

assign p_Result_16_fu_500_p3 = {{p_Result_14_reg_541_pp0_iter22_reg}, {31'd0}};

assign p_Result_17_fu_489_p3 = {{p_Result_14_reg_541_pp0_iter22_reg}, {31'd1070141403}};

assign p_Result_18_fu_478_p3 = {{p_Result_14_reg_541_pp0_iter22_reg}, {31'd1078530011}};

assign p_Result_19_fu_467_p3 = {{p_Result_14_reg_541_pp0_iter22_reg}, {31'd0}};

assign p_Result_20_fu_456_p3 = {{p_Result_14_reg_541_pp0_iter22_reg}, {31'd1070141403}};

assign p_Result_21_fu_361_p3 = {{1'd0}, {trunc_ln368_fu_357_p1}};

assign p_Result_22_fu_378_p3 = {{1'd0}, {trunc_ln368_1_fu_374_p1}};

assign p_Result_s_fu_197_p3 = data_V_fu_193_p1[32'd31];

assign select_ln809_fu_449_p3 = ((p_Result_14_reg_541_pp0_iter22_reg[0:0] == 1'b1) ? 32'd3217625051 : 32'd1070141403);

assign tmp_1_fu_321_p4 = {{data_V_fu_193_p1[22:8]}};

assign tmp_2_fu_331_p3 = {{tmp_1_fu_321_p4}, {or_ln766_fu_315_p2}};

assign tmp_3_fu_429_p3 = {{p_Result_s_reg_536_pp0_iter19_reg}, {p_Result_14_reg_541_pp0_iter19_reg}};

assign tmp_458_fu_215_p1 = data_V_fu_193_p1[22:0];

assign tmp_459_fu_231_p4 = {{data_V_4_fu_219_p1[30:23]}};

assign tmp_460_fu_241_p1 = data_V_4_fu_219_p1[22:0];

assign tmp_fu_205_p4 = {{data_V_fu_193_p1[30:23]}};

assign trunc_ln368_1_fu_374_p1 = data_V_fu_193_p1[30:0];

assign trunc_ln368_fu_357_p1 = data_V_4_fu_219_p1[30:0];

assign trunc_ln766_fu_311_p1 = data_V_fu_193_p1[7:0];

assign xor_ln18_1_fu_275_p2 = (icmp_ln757_1_fu_269_p2 ^ 1'd1);

assign xor_ln18_fu_251_p2 = (icmp_ln757_fu_245_p2 ^ 1'd1);

assign xor_ln822_fu_439_p2 = (bitcast_ln822_fu_435_p1 ^ 32'd2147483648);

assign xor_ln826_fu_525_p2 = (bitcast_ln826_fu_522_p1 ^ 32'd2147483648);

always @ (posedge ap_clk) begin
    a_reg_595[31] <= 1'b0;
    a_reg_595_pp0_iter1_reg[31] <= 1'b0;
    b_reg_602[31] <= 1'b0;
    b_reg_602_pp0_iter1_reg[31] <= 1'b0;
end

endmodule //stereolbm_accel_atan2_cordic_float_s
